### PR TITLE
fix span name indexing

### PR DESCRIPTION
**Pull request by danchia**
TraceIds indexed by spanNames were not always showing up if your span name had capital letters. This fixes the ingestion to be consistent.

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
mind adjusting and adding a test like this to SpanStoreSpec that shows what expectations are? I'm not saying that the below test is what we want, just an example of how to write one.

```
  @Test def spanNamesGoLowercase() {
    result(store(Seq(span1.copy(name = "Yak"))))

    result(store.getSpanNames("service")) should be(List("yak"))
    result(store.getTraces(QueryRequest("service", Some("Yak")))) should be(empty)
    result(store.getTraces(QueryRequest("service", Some("yak")))) should be(
      Seq(span1.copy(name = "yak"))
    )
  }
```

**Comment by danchia** [comment]
Happy to do so :)

**Comment by danchia** [comment]
@adriancole added a test as requested

**Comment by codefromthecrypt** [comment]
Thanks! Lg on green

Nit:

Lets avoid forcing navigation to see what test input thats only used once is. I know many tests in zipkin are like that, but it is bad practice as it adds unnecessary and distracting indirection. In some cases, for example, I've found misnamed variables hiding bugs. Inlining eliminates that problem space.

**Comment by codefromthecrypt** [comment]
To add more to my Nit (digging a deeper hole):

I should say inlining or locally declaring input where only used once. Ex. A misnamed variable is obvious when it is declared and used within the same few lines. Your variable is fine, just people do refactors and break things. Locals or inlining is great as say a future PR breaks this, you can usually see in the diff its context, whereas if the input is declared at the top of the file, you cant.

**Comment by codefromthecrypt** [comment]
Lemme know if I lost you. Apologies if I over communicated. I don't mind
helping to get this merged.

**Comment by danchia** [comment]
Whoops. @adriancole I've updated the diff, but forgot to ping you. I don't know why it's failing though. Can you trigger a retest? It works locally for me.

**Comment by codefromthecrypt** [comment]
sure.. kicking now

**Comment by codefromthecrypt** [comment]
sure you are pushed (and doing ./gradlew clean check from root)? test fail looks legit:

```
*** 1 TEST FAILED ***
AnormSpanStoreSpec:
- spanNamesGoLowercase *** FAILED ***
  org.scalatest.exceptions.TestFailedException: List("SPAN_NAME") was not equal to List("span_name") (SpanStoreSpec.scala:226)
```

**Comment by danchia** [comment]
Ah good catch.. clean surfaced the failure. Silly incremental.
Fixing now.

**Comment by danchia** [comment]
@adriancole I lowercased the spanName in the `Span` constructor to normalize is, as discussed in gitter.

**Comment by codefromthecrypt** [comment]
Looks simple enough. Can you add a note to zipkinCore.thrift under span name that these are lowercase? I know it is separate issues, but extremely similar is the service name. Is that easy enough to address in this PR?

**Comment by codefromthecrypt** [comment]
thanks tons

**Pull request merged**
