### PR TITLE
new KafkaSpanReceiver

### PR DESCRIPTION
**Pull request by fr0stbyte**
This is a relatively generic KafkaConsumer, an example on how to write a specific decoder is in the tests

### CODE REVIEW

**Comment by sprsquish** [comment]
This looks good. I got backed up with other stuff today, but will pull it internally tomorrow. Thanks!

**Comment by fr0stbyte** [comment]
Also wanted to say that I'm working on adding stats and also allowing the collector to be configured via zookeeper. Don't have timeline for these yet.

**Comment by suchang** [comment]
LGTM

**Comment by sprsquish** [comment]
@fr0stbyte please merge master.

The build file changed recently and hadn't been pushed to GitHub in a while. When I tried to pull this PR in it failed due to a conflict.

**Comment by fr0stbyte** [comment]
@sprsquish just rebased off upstream/master can you please try again ?

**Comment by sprsquish** [comment]
Thanks! Pulled internally. I have a few tweaks to make then it'll get pushed back here.

**Comment by sprsquish** [comment]
Closed by: 6107d9b
Thank you!

**Pull request closed without merging**
