### PR TITLE
[Feedback Needed] Show Pie charts and tables instead of badges for span counts

### PR DESCRIPTION
**Pull request by tacigar**
in #3180, we had a discussion about how to display span counts.
At that time I created a chart with the following design, but we found some problems for usability.

**rejected design**:
OLD CHART

So I created a new design with pie chart and table like the following:

**new design**:
スクリーンショット 2020-09-20 17 25 14

What do you think about this? Please give me your feedback.

cc @adriancole @shakuzen

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
note: I still owe a change to make those numbers better (#3192).. we should be counting entry spans (local roots) not ad-hoc spans. That said, the UX wouldn't change

**Comment by shakuzen** [comment]
Thanks for the continued effort and design work here, @tacigar. Great stuff! In a lot of ways, I like this much more. I worry, though, if we don't make it clear that the pie chart is showing span count, users will think it is a representation of relative duration. Even if we tried to make it clear, I worry if users will still jump to that conclusion. Likewise, the table with the span count almost aligns with the duration column from the search results, which again might lead people to think it is a duration value. I wonder if we need both the pie chart and the table, since the names of the services are clearly visible on the pie chart. Depending on how important seeing the exact numbers are, maybe just a pie chart is enough?

**Comment by codefromthecrypt** [comment]
I'll also note that in design cases we aren't using a trace with a large amount of service names. The earlier design (bucketing by first letter) could equally be done in pie form, as could bars without bucketing by service name. I think we are still in need of a representative trace that has a lot of service names in it. @mrajah-twttr would you be up to contributing a realistic trace with a larger amount of service names in it?

**Comment by mrajah-twttr** [comment]
typically we have large number of spans and not large number of services.. how many services are you looking at

**Comment by codefromthecrypt** [comment]
> typically we have large number of spans and not large number of services.. how many services are you looking at

any trace with more than 20 service names would cause some design impact I think

**Comment by mrajah-twttr** [comment]
i would not be able to give the trace without a bunch of manual scrubbing but i can try it out and post screenshot. stay tuned.

**Comment by mrajah-twttr** [comment]
This looks pretty cool. 
image

Couple of points. 

1. Would be good to know the distinct service counts somewhere
2. When clicking on anyone color would help to hide the rest of the labels else its too cluttered sometimes (is it better to show names only for big pieces and show names for others only on hover?)
3. When selecting a particular service would help to highlight/scroll it on the right side table or move it to top.

**Comment by codefromthecrypt** [comment]
It has been a long time since we cut a version and we need to..

We should decide soon if what's in master is ok, if this should be included, or if something should be reverted.

Those using the UI, do you have any concerns if master shipped as-is, or if this change as-is was merged?

**Comment by jorgheymans** [comment]
For me master can ship as is, and we should not yet include this.

**Comment by llinder** [comment]
I'm going to pull down this code to check out the UI changes later this evening.  I don't want to hold up decisions to release or not but if folks want I wouldn't mind setting up a 15 minute demo internally at work and gathering some additional input to share here.

**Comment by codefromthecrypt** [comment]
thanks for the offer @llinder!

**Pull request closed without merging**
