### PR TITLE
Add support for elasticsearch 8

### PR DESCRIPTION
**Pull request by fazilali**
**Issue** - https://github.com/openzipkin/zipkin/issues/3468

- Not able to connect zipkin with elasticsearch 8.* version

**Solution**
- Add version 9 to avoid the check with version 8

### CODE REVIEW

**Comment by shakuzen** [comment]
I'm not sure why CI isn't running on this pull request. Could you please try pushing a commit again to trigger it?

**Comment by rcomanne** [comment]
Can we get this merged?

**Comment by shakuzen** [comment]
@jcchavezs I've added the source for a zipkin-elasticsearch8 test image which is needed to run the integration test, but the CI here can't pull the test image because it hasn't been pushed yet. It's a bit of a chicken and egg situation.

**Comment by fazilali** [comment]
@shakuzen How can we get this PR merged?

**Comment by wu-sheng** [comment]
Elasticsearch8 would be supported on 3.x. 3.0.0-alpha1 will be cut soon.

**Comment by codefromthecrypt** [comment]
thanks for the maintenance attempt @fazilali. I opened [this issue](https://github.com/openzipkin/zipkin/issues/3605) about an alternative future for zipkin v3. That said, I personally believe that v2 should be fixed, to know tests work before change. Monday, I'll try your change.

**Comment by codefromthecrypt** [comment]
to start this, we need an ES 8 image. I'll work on this.

**Comment by codefromthecrypt** [comment]
FYI ES changed their license after version 7.10, so it is no longer "OSS", but I suspect it is ok for us package a docker image like we did before, as it is a test image and not used for anything otherwise. cc @xeraa

**Comment by codefromthecrypt** [comment]
Zipkin 2.25 will target ES 8 per https://github.com/openzipkin/zipkin/releases/tag/2.24.4 We have some work to do next week including sourcing an image

**Comment by codefromthecrypt** [comment]
first step is making our ES 7 image use the Elastic licensed distribution. I am working on this.

**Comment by codefromthecrypt** [comment]
please see notes at the bottom of #3468 about the base docker image, which is needed before this can proceed. If someone has time, please work on it in the next couple weeks, as the base project is totally ready for maintenance and change again.

**Review by codefromthecrypt — APPROVED** [review]
I had to do only minimal changes to get tests passing. Thanks tons @fazilali!

**Comment by codefromthecrypt** [comment]
let's merge this after https://github.com/openzipkin/zipkin/pull/3666 as it should be in a new minor, followed by a change to remove testing for ES 6 (which is no longer supported by Elastic)

**Pull request merged**
