### PR TITLE
add a button to view the raw json of a search query

### PR DESCRIPTION
**Pull request by cburroughs**
Easy access to the raw json can aid in debugging.  Uses the same panel
as the per trace json display.

ref #1143

### CODE REVIEW

**Comment by cburroughs** [comment]
q-json-0
q-json-1

**Comment by codefromthecrypt** [comment]
oh interesting.. this is the raw json for all the results. the single span in the result list threw me off :)

I can see this as valuable, but wonder if for first timers if this isn't distracting? maybe others can comment cc @openzipkin/core

**Comment by cburroughs** [comment]
> oh interesting.. this is the raw json for all the results.

Wasn't that your proposal in #1143?

**Comment by codefromthecrypt** [comment]
lol wow you are actually going through the backlog! thanks. sorry I forgot
about my own issue :P

**Comment by codefromthecrypt** [comment]
so TBH I don't have a better suggestion for where/how to present the json button. with that context in mind, I think it will help with debugging as currently we ask people to use curl.

will merge tomorrow unless feedback suggests against. Thanks again!

nit: it isn't really "raw" since the list api doesn't have that option. in the get trace api, raw indicates no adjustments to the data. http://zipkin.io/zipkin-api/#/paths/%252Ftrace%252F%7BtraceId%7D/get/parameters/raw

**Pull request merged**
