### PR TITLE
collector: add kafka store

### PR DESCRIPTION
**Pull request by franklinhu**
Add module that allows users to write their spans from the collector to a Kafka queue

### CODE REVIEW

**Comment by caniszczyk** [comment]
Looks like Kafka is being moved to the ASF incubator which is good:
https://github.com/apache/kafka

What sucks is they have no releases yet there.

We should probably start adding a NOTICE (e.g., https://github.com/twitter/scalding/blob/develop/NOTICE) file to track these third party dependencies...

**Comment by caniszczyk** [comment]
Apparently there is a 0.7.1 release... not available on any maven repo that I can find...

http://incubator.apache.org/kafka/downloads.html

**Comment by franklinhu** [comment]
They didn't seem to have an official Scala 2.9.\* build, and the 2.8 jar is ABI incompatible with 2.9. I just used one that @jasonjckn published on clojars. I'll add the NOTICE file.

**Comment by johanoskarsson** [comment]
+1. Perhaps add a readme describing the module but also mentioning that it is experimental as per your email.

**Pull request closed without merging**
