### PR TITLE
Change endTs when enter key or search button is clicked

### LINKED ISSUE #2364: endTs remains unchanged in Zipkin Lens
## Describe the Bug

`endTs` seems to remain unchanged until refreshing the page entirely (F5).
so new traces wouldn't come when clicking the lens icon

image

If this behavior is intentional, it would be nice to provide a refresh button.

## Steps to Reproduce

Enable Zipkin Lens => Click 🔍 => Change search criteria or Go to dependencies page and back to search page => click  🔍 again

## Expected Behaviour

I'd like to update traces without reloading the page

### PR DESCRIPTION
**Pull request by tacigar**
fixes #2364

### CODE REVIEW

**Comment by tacigar** [comment]
Now.

When custom lookback is not set, endTs will be changed.

endts1

When custom lookback is set, endTs will not be changed, because endTs is fixed.

endTs2

**Comment by codefromthecrypt** [comment]
cc @making

**Comment by making** [comment]
Looks great 👍

**Comment by jcchavezs** [comment]
I love this fix!!! Could we please do a release @adriancole?

**Pull request merged**
