### PR TITLE
Fix traces rendering with numeric-like `serviceNames`

### PR DESCRIPTION
**Pull request by dos65**
In case when we have `serviceNames` that looks like numbers, `data` function from jQuery returns it as `number` that leading to error, because `number` doesn't have method `split`.

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
Thanks! Can you attempt a unit test to ensure this stays fixed?

**Comment by dos65** [comment]
Ok, I will do it.

**Comment by codefromthecrypt** [comment]
ping (aka nag :) )

**Comment by dos65** [comment]
@adriancole oh, sorry for waiting. I started investigating how to test `TraceUI` component, but it's not so obvious for me.

**Comment by codefromthecrypt** [comment]
test probably means extracting an exported function for `setupSpan` like we do for `showSpans`. then you can test it in trace.test.js

lemme know if you want more clues

**Comment by dos65** [comment]
@adriancole it was good idea to test it, fix was incomplete )

**Comment by codefromthecrypt** [comment]
Thanks and good work!

**Pull request merged**
