### PR TITLE
Removes zipkin-query gem

### PR DESCRIPTION
**Pull request by codefromthecrypt**
The zipkin-query gem is out-of-date, untested and full of tech debt
such as TODOs and hard-coded hosts and paths. Internally at Twitter, I
can find no use of it. Its only change was one day after it was written,
over three years ago.

I tried fixing thrifts, regenerating code, etc., but I think it is clear
this effort could be put on more important tasks. Hence, let's remove
the zipkin-query gem.

### CODE REVIEW

**Comment by mosesn** [comment]
+1, looks like it was useful for some zipkin maintainer's workflow, but if it's not useful for yours, reinventing it doesn't look that hard (and git will still have it in the future).

**Comment by rtyler** [comment]
@adriancole LGTM, I'll create a new repo for the gem elsewhere

**Comment by codefromthecrypt** [comment]
@rtyler thx the tracer gem and the browser plugin both seem like they're better off in their own repos

**Comment by codefromthecrypt** [comment]
closed via 743e8470f3b4ed7c950a3610060807b6241e3b7c

**Comment by codefromthecrypt** [comment]
FYI this gem is archived here https://github.com/openzipkin/zipkin-query

**Pull request closed without merging**
