### PR TITLE
Set default spanIndex based on spanId specified in URL hash

### PR DESCRIPTION
**Pull request by mrajah-twttr**
Set default spanIndex based on spanId specified in URL hash, this should scroll to the span, open up the span and highlight it

Need some guidance on how to make it scroll. the change currently works to highlight and open the details of the appropriate span @jorgheymans

### CODE REVIEW

**Comment by jorgheymans** [comment]
Thanks, i have requested a review from our UI guru @tacigar as i'm not into the details at all on anything typescript related. 

Original comment this PR is based on: https://github.com/openzipkin/zipkin/pull/3162#issuecomment-670926360

**Comment by jcchavezs** [comment]
I am curious about what happens when we have a local root that does not show the aimed span. Maybe we change the local root? cc @adriancole

**Comment by tacigar** [comment]
Thanks, about for scrolling, an external library such as react-scroll may be helpful...
https://github.com/fisshy/react-scroll

**Comment by tacigar** [comment]
Clicking a span twice will redisplay that span as the root.

reroot

Perhaps it would be easier to display this rerooted diagram than scrolling to the span...

**Comment by codefromthecrypt** [comment]
very much agree that moving back from re-rooting should use the new anchor. I think we discussed moving back to an anchor in the first development of re-root, just we didn't have the fully formed idea for anchoring yet

**Pull request closed without merging**
