### PR TITLE
feat: add extraEnv to chart

### LINKED ISSUE #3429: helm-chart - JAVA_OPTS support
There is no possibility to set JAVA_OPTS in helm chart.  Right now we are using "elasticsearch" as STORAGE_TYPE and [start-zipkin](https://github.com/openzipkin/zipkin/blob/master/docker/start-zipkin) file uses hardcoded values (  JAVA_OPTS=${JAVA_OPTS:-"-Xms32m -Xmx32m -XX:+ExitOnOutOfMemoryError"} in this case)

## Feature
Additional value for JAVA_OPTS handled by helm chart should be supported.

## Rationale
Rightnow zipkin takes hardcoded values that are not working with elasticsearch ( no more than 100 values can be shown in zipkin because of Terminating due to java.lang.OutOfMemoryError: Java heap space

## Example Scenario
This will help with setting up values for java to zipkin be able to show more than 100 results (in case of elasticsearch is used)

### PR DESCRIPTION
**Pull request by jonkerj**
This allows users to specify additional environment variables, such as JAVA_OPTS. This fixes #3429.

### CODE REVIEW

**Comment by jonkerj** [comment]
@mrfelek : you've requested this change, could you maybe look into it? ;-)

**Comment by mrfelek** [comment]
@jonkerj Hi. Sorry I don't have access to that project anymore 😞
I can't check it

**Comment by jonkerj** [comment]
Ok, @jcchavezs maybe? I'd like to clean up my personal PR list and this one is dangling

**Comment by jcchavezs** [comment]
Sure, let me check.

**Comment by Loic-R** [comment]
Hello,
Nice work @jonkerj , it would be great to be able to add extra env, I have the exact same need and today, need to manually patch the deployment. 
@jcchavezs Is there any other reasons than the conflict with main branch for this PR not merged?

**Comment by jonkerj** [comment]
I sort of lost interest in fixing this (year old) bug, as it does not affect me/us and getting a dev to actually look at seems tricky. Feel free to continue this, though

**Comment by Loic-R** [comment]
Yes sure thanks for the fast answer

**Review by jcchavezs — APPROVED** [review]

**Pull request merged**
