### PR TITLE
switched to gen.Span and some minor improvements

### PR DESCRIPTION
**Pull request by fr0stbyte**

### CODE REVIEW

**Comment by sprsquish** [comment]
Thanks for this @fr0stbyte. Can you make the change against master though? I made some edits on the original PR mostly to match the style of the rest of the project.

**Comment by fr0stbyte** [comment]
I noticed that some code was looking strangely unfamiliar. 
Two questions : 
1. here https://github.com/twitter/zipkin/commit/6107d9b#diff-f70d68ae7ea4c895a87b3be96ca84af6R15 
   why is the trait moved down as an internal type of KafkaProcessor ? Decoder[Option[List[Span]]]] is used somewhere else in the code, plus the implementing collectors would use it. Can we keep it top level and use it throughout the project ? 
2. https://github.com/twitter/zipkin/pull/390/files#diff-edc7ec48aa7cab8b9004553848474e92R22 the flag is a `,` separated sequence of type `a=b`. Without the definition of the flag, how will the system understand `-zipkin.kafka.topics=a=1,b=2,c=3` ?

**Comment by sprsquish** [comment]
1. It's never used as a trait. The process doesn't take a `KafkaDecoder` it takes a `Decoder[Option[List[Span]]]` (I think that's the right approach, btw). Having it as a trait doesn't really mean anything. It's used as a type alias, so I made that explicit. 
2. Flag already provides a map type: https://github.com/twitter/util/blob/master/util-app/src/main/scala/com/twitter/app/Flag.scala#L86

**Comment by fr0stbyte** [comment]
Sure, not as a trait but as a type then ? 
Didn't know about the map type, thanks for that.

**Comment by sprsquish** [comment]
Types have to be defined inside something. We could put it in a package object, but there's little different between doing that and leaving it where it is.

**Comment by fr0stbyte** [comment]
Got it. Please check the updated diff.

**Comment by fr0stbyte** [comment]
@sprsquish bump

**Comment by sprsquish** [comment]
@fr0stbyte hey. sorry. I've been pretty buried. I don't think I'm going to have the change to get to this until next week.

**Comment by sprsquish** [comment]
pulled internally will show up here soon.

**Pull request closed without merging**
