### PR TITLE
Allowing for 'false' values in config.

### PR DESCRIPTION
**Pull request by Logic-32**
Fixes issue mentioned at https://github.com/openzipkin/zipkin/pull/1903#issuecomment-372857764.

### CODE REVIEW

**Comment by Logic-32** [comment]
Not sure why I had a test failure in Travis... it passed on my box :(

**Comment by codefromthecrypt** [comment]
circleci likely failed due to degraded service (it timed out)

**Comment by codefromthecrypt** [comment]
Thanks! I will add a unit test to your PR

**Comment by codefromthecrypt** [comment]
ok 3 hours to figure out how to test false === false, but... at least next time we need an api test we know what to copy/paste :)

**Review by shakuzen — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
screen shot 2018-03-24 at 2 55 59 pm

**Comment by codefromthecrypt** [comment]
thanks much!

**Comment by Logic-32** [comment]
Yw!  Thank you for adding the test :)

**Pull request merged**
