### PR TITLE
Test split travis build with env

### PR DESCRIPTION
**Pull request by eirslett**
If you look at the Travis build, this is one way to go. Splitting up the build into smaller pieces allows us to isolate failure, and work around the problem of resource usage.
The flip side is that we use more resources, since we have to bootstrap sbt and download dependencies for every submodule.

PS: do not merge

### CODE REVIEW

**Comment by rtyler** [comment]
that's some split!

**Comment by codefromthecrypt** [comment]
Hehe love the 'ps'

**Comment by codefromthecrypt** [comment]
I like this, but I'm concerned about the >2hrs feedback time. I think that is too long.. a cure worse than the disease. Do you feel otherwise?

**Comment by eirslett** [comment]
Two hours is too long, yes. This might not be a good option after all...

**Comment by eirslett** [comment]
I'll close this one.

**Pull request closed without merging**
