### PR TITLE
Extract javax.annotation-api version into parent pom.xml

### PR DESCRIPTION
**Pull request by reta**
Follow-up on https://github.com/openzipkin/zipkin/pull/3284, extracting `javax.annotation-api` version into parent `pom.xml`

### CODE REVIEW

**Comment by reta** [comment]
CC @adriancole please :)

**Review by codefromthecrypt — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
build break is because a sneaky hidden dependency on docker hub!

```
  E: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/bionic/InRelease  402  Payment Required [IP: 54.193.34.251 443]
```

Full output
```
 /usr/bin/sudo add-apt-repository deb [arch=amd64,arm64] https://download.docker.com/linux/ubuntu bionic stable
  Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
  Get:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
  Get:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
  Hit:4 https://storage.googleapis.com/bazel-apt stable InRelease
  Get:5 http://dl.google.com/linux/chrome/deb stable InRelease [1811 B]
  Get:7 https://download.docker.com/linux/ubuntu bionic InRelease [64.4 kB]
  Get:8 http://packages.cloud.google.com/apt cloud-sdk InRelease [6349 B]
  Hit:9 https://download.mono-project.com/repo/ubuntu stable-bionic InRelease
  Ign:10 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 InRelease
  Hit:11 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 Release
  Hit:13 https://dl.yarnpkg.com/debian stable InRelease
  Get:12 https://cli-assets.heroku.com/apt ./ InRelease [2879 B]
  Get:14 http://ppa.launchpad.net/ansible/ansible/ubuntu bionic InRelease [15.9 kB]
  Get:6 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [8993 B]
  Get:15 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
  Get:16 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease [103 kB]
  Get:17 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  InRelease [1613 B]
  Get:18 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1727 kB]
  Hit:19 http://ppa.launchpad.net/apt-fast/stable/ubuntu bionic InRelease
  Get:20 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [367 kB]
  Ign:21 https://dl.bintray.com/sbt/debian  InRelease
  Get:22 http://azure.archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [184 kB]
  Err:23 https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease
    402  Payment Required [IP: 54.193.34.251 443]
  Get:24 http://azure.archive.ubuntu.com/ubuntu bionic-updates/restricted Translation-en [24.6 kB]
  Get:25 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1683 kB]
  Get:26 http://azure.archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [354 kB]
  Get:27 https://dl.bintray.com/sbt/debian  Release [815 B]
  Get:28 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease [20.8 kB]
  Get:29 http://ppa.launchpad.net/hvr/ghc/ubuntu bionic InRelease [15.3 kB]
  Get:30 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1089 B]
  Get:31 https://download.docker.com/linux/ubuntu bionic/stable arm64 Packages [12.9 kB]
  Get:32 https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages [13.0 kB]
  Get:33 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease [20.8 kB]
  Get:34 http://packages.cloud.google.com/apt cloud-sdk/main amd64 Packages [144 kB]
  Hit:36 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic InRelease
  Get:37 https://cli-assets.heroku.com/apt ./ Packages [620 B]
  Get:38 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  Packages [6389 B]
  Get:39 http://ppa.launchpad.net/ansible/ansible/ubuntu bionic/main amd64 Packages [820 B]
  Get:40 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main amd64 Packages [229 kB]
  Get:41 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1400 kB]
  Get:43 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic/main amd64 Packages [3048 B]
  Get:44 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [277 kB]
  Get:45 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [166 kB]
  Get:46 http://security.ubuntu.com/ubuntu bionic-security/restricted Translation-en [22.1 kB]
  Get:47 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1079 kB]
  Get:48 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [241 kB]
  Get:49 http://ppa.launchpad.net/hvr/ghc/ubuntu bionic/main amd64 Packages [11.6 kB]
  Get:50 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages [80.3 kB]
  Reading package lists...
  E: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/bionic/InRelease  402  Payment Required [IP: 54.193.34.251 443]
  E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease' is no longer signed.
```

**Comment by codefromthecrypt** [comment]
This seems to have executed after the install, so the remedy in the action to swallow exceptions seems ok for now https://github.com/docker-practice/actions-setup-docker/commit/5adf8505b047d11d321093d5b96e291effc0f3c8

**Comment by reta** [comment]
That was unexpected ... thanks a lot for digging into it, @adriancole

**Comment by codefromthecrypt** [comment]
merging this despite red as the docker install fail is unrelated entirely

**Comment by reta** [comment]
Thanks @adriancole !

**Comment by codefromthecrypt** [comment]
no prob thanks for putting the effort in here. it is nice to have a partner in crime

**Pull request merged**
