### PR TITLE
Add autocompleteTags feature to zipkin-lens

### PR DESCRIPTION
**Pull request by tacigar**

### CODE REVIEW

**Comment by tacigar** [comment]
Almost finished.
But there are still some problems left...

**Review by zeagord — COMMENTED** [review]
LGTM

**Comment by codefromthecrypt** [comment]
will check this in my flight now

**Comment by codefromthecrypt** [comment]
I lied about checking in the flight. I am such a deviant. checking now

**Review by codefromthecrypt — APPROVED** [review]
from a code POV I like this as it slides right in without any additional configuration. While in later change we might want to add things like friendly names, tool tips etc. there is no reason to do so now. I will now test the change itself, and if successful will merge since others already approve.

**Comment by codefromthecrypt** [comment]
tested like this (note I will change the variable for changing the source root in the armeria change)

```bash
$ AUTOCOMPLETE_KEYS=client_cluster_name,country java -jar ./zipkin-server/target/zipkin-server-*exec.jar --zipkin.ui.source-root=classpath:zipkin-lens
```

```bash
$ cd zipkin-ui/testdata
$ curl -X POST -s localhost:9411/api/v2/spans -H'Content-Type: application/json' -d @netflix.json
$ open 'http://localhost:9411/zipkin/?lookback=custom&startTs=1'
```

done

cc @narayaruna @making @drolando fun right?

**Pull request merged**
