### PR TITLE
Fix java.lang.UnsupportedOperationException: empty.min error

### PR DESCRIPTION
**Pull request by noslowerdna**
This pull request fixes a couple similar exceptions that we've seen when querying for nonexistent annotations.

a)

```
ERR [20150528-17:13:02.755] query: java.lang.UnsupportedOperationException: empty.min
ERR [20150528-17:13:02.755] query:     at scala.collection.TraversableOnce$class.min(TraversableOnce.scala:194)
ERR [20150528-17:13:02.755] query:     at scala.collection.immutable.List.min(List.scala:76)
ERR [20150528-17:13:02.755] query:     at com.twitter.zipkin.query.QueryService$$anonfun$getTraceIds$1$$anonfun$apply$9$$anonfun$apply$11$$anonfun$11.apply(QueryService.scala:161)
```

b)

```
ERR [20150625-16:42:41.283] query: java.lang.UnsupportedOperationException: empty.min
ERR [20150625-16:42:41.283] query:     at scala.collection.TraversableOnce$class.min(TraversableOnce.scala:194)
ERR [20150625-16:42:41.283] query:     at scala.collection.mutable.ArrayBuffer.min(ArrayBuffer.scala:47)
ERR [20150625-16:42:41.283] query:     at com.twitter.zipkin.query.QueryService$$anonfun$getTraceIds$1$$anonfun$apply$7.apply(QueryService.scala:147)
```

The exceptions can be easily reproduced by searching for a) an annotation that doesn't exist or b) two or more annotations that do not exist.

### CODE REVIEW

**Comment by noslowerdna** [comment]
Related issue: https://github.com/twitter/zipkin/issues/309

**Comment by codefromthecrypt** [comment]
LGTM

**Comment by codefromthecrypt** [comment]
thanks, @noslowerdna, appreciate you taking time to resolve this w/ test cases

**Comment by codefromthecrypt** [comment]
closed via 6f478dbf0aa91244dfb0195d5c0ea40ab09b7d43

**Pull request closed without merging**
