### PR TITLE
Filters

### PR DESCRIPTION
**Pull request by afalko**
@rmichela

This didn't work, so I'm going to pump something out by doing reflection myself rather than trying to get Spring to do it. 

Here is the example filter: https://github.com/afalko/ExampleSpanFilter

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
Hi there. don't forget to link issues when making pull requests ad folks might not know the overall plan.

as mentioned this might end up in the v2 package but regardless thanks for the spike

**Comment by afalko** [comment]
Please accept my appologies @adriancole. I meant to make this a PR to my own fork before blasting it out to the community. I'll close it and create a proper one when I'm ready.

**Comment by codefromthecrypt** [comment]
no worries.. glad to see wheels turning

**Comment by codefromthecrypt** [comment]
ps this might give a general structure for add-ons https://github.com/openzipkin-attic/zipkin-sparkstreaming-example I'd expect we'd want something like this, like you can just add to the classpath and go

**Comment by afalko** [comment]
Thanks for the pointer! @rmichela was able to get the add-classpath-and-go part working in the sample plugin: https://github.com/afalko/ExampleSpanFilter/pull/1

It works e2e, so stay tuned :)

**Pull request closed without merging**
