### PR TITLE
Removes experimental zipkin-kafka module

### LINKED ISSUE #492: zipkin-kafka indirectly depends on dead libraries
zipkin-kafka has a complex build in part due to dependency on dead libraries via tormenta-kafka. This results in us having special resolvers like so. I wonder if we can integrate with kafka without pulling in a dependency tree like this.

```
// for storm-kafka
resolvers += "clojars" at "https://clojars.org/repo"
// com.twitter:kafka
resolvers += "conjars" at "http://conjars.org/repo"
```

### PR DESCRIPTION
**Pull request by codefromthecrypt**
zipkin-kafka is fragile as it depends on dead libraries. It doesn't have
obvious adoption and should be removed.

Closes #492

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
@eirslett @jamescway

**Comment by abesto** [comment]
How is `zipkin-kafka` related to `zipkin-receiver-kafka` (if at all)?

**Comment by eirslett** [comment]
Nobody even knows what zipkin-kafka is... Nuke it! :boom:

**Comment by codefromthecrypt** [comment]
@abesto it looked like a partially implemented sink for spans (as opposed to scribe). Its partial implementation, rotty deps, and lack of any tests say "delete me!"

**Comment by jamescway** [comment]
@abesto, not related at all, :+1: to killing it

**Comment by abesto** [comment]
Cool, cool. I'm all for removing dead code.

**Pull request merged**
