### PR TITLE
Update Armeria dependency

### PR DESCRIPTION
**Pull request by minwoox**
- Armeria 1.2.0 -> 1.3.0
- Jackson 2.11.3 -> 2.12.0
- Netty 4.1.53.Final -> 4.1.54.Final

### CODE REVIEW

**Comment by minwoox** [comment]
https://github.com/openzipkin/zipkin/pull/3320/checks?check_run_id=1483761327#step:5:775
The build failed. Do you have any idea about this? 🤔

**Comment by codefromthecrypt** [comment]
strange unrelated error. will look into it.

```
<<< FAILURE! - in zipkin2.collector.kafka.ITKafkaCollector
Error:  zipkin2.collector.kafka.ITKafkaCollector  Time elapsed: 24.158 s  <<< ERROR!
java.lang.IllegalArgumentException: Requested port (19092) is not mapped
	at 
```

**Comment by minwoox** [comment]
Thanks!

**Comment by codefromthecrypt** [comment]
you can try to rebase now. should be all good as I fixed the kafka test image

**Comment by codefromthecrypt** [comment]
rolling the dice :) thanks!

**Comment by minwoox** [comment]
Oops thanks a lot. 🙇‍♂️

**Pull request merged**
