### PR TITLE
[zipkin-ui] Add hash to filename of app[.min].{js,css}[.map]

### PR DESCRIPTION
**Pull request by abesto**
The inside of the .jar list looks like this after the change:

```
META-INF/
META-INF/MANIFEST.MF
zipkin-ui/
zipkin-ui/448c34a56d699c29117adc64c43affeb.woff2
zipkin-ui/614fad616d014daf5367e068505cad35.png
zipkin-ui/89889688147bd7575d6327160d64e760.svg
zipkin-ui/8b55a822e72b8fd5e2ee069236f2d797.png
zipkin-ui/app-8f28873f153b2b06e7ab.min.css
zipkin-ui/app-8f28873f153b2b06e7ab.min.css.map
zipkin-ui/app-8f28873f153b2b06e7ab.min.js
zipkin-ui/app-8f28873f153b2b06e7ab.min.js.map
zipkin-ui/e18bbf611f2a2e43afc071aa2f4e1512.ttf
zipkin-ui/f4769f9bdb7466be65088239c12046d1.eot
zipkin-ui/fa2772327f55d8198301fdb8bcfc8158.woff
zipkin-ui/index.html
```

### CODE REVIEW

**Comment by eirslett** [comment]
If you cd zipkin-ui and npm run dev, will it still work? Live-reload etc.?

**Comment by abesto** [comment]
:O Why would that change? Checking...

Edit: oh I see, not sure that filename changes are picked up by live reload. Still checking.

**Comment by abesto** [comment]
With `npm run dev` the site doesn't load, I get a bad gateway for config.json. Assuming it wants to proxy to zipkin-web (makes sense), so I did `./gradlew zipkin-web:run`. But zipkin-web gives me a 500 with this unhelpful message in the console:

```
E 0322 16:31:25.350 THREAD21: Exception propagated to the root monitor!
com.twitter.finagle.FailedFastException: Endpoint zipkin-web is marked down. For more details see: https://twitter.github.io/finagle/guide/FAQ.html#why-do-clients-see-com-twitter-finagle-failedfastexception-s
    at com.twitter.finagle.NoStacktrace(Unknown Source)
```

This is on `master` on a clean build. Unfortunately I'm out of time to spend on this ATM; if you can quickly verify that this PR works, that's much appreciated. Otherwise I'll have more time tonight.

**Comment by eirslett** [comment]
Try starting zipkin-query instead of zipkin-web?
And it looks like the documentation is outdated, too...
The "Developing" section must be moved from zipkin-web/README.md to zipkin-ui/README.md.
And we need to update webpack.config.js so that it proxies to port 9411 (the query server directly) instead of 8080 (web).

**Comment by eirslett** [comment]
But I tested this change, it works with livereload!

**Comment by abesto** [comment]
Awesome, thanks! Hope that'll be a nice wake-up present for @adriancole :)

**Comment by codefromthecrypt** [comment]
indeed. thanks!

**Pull request merged**
