### PR TITLE
TwitterServer based Collector

### PR DESCRIPTION
**Pull request by sprsquish**
Also included is a ScribeReceiver and an example project that shows how
a collector listening to scribe and writing to cassandra would be wired
up.

This is based on the span-store branch and is blocked by it's approval,

### CODE REVIEW

**Comment by bmdhacks** [comment]
What kind of testing has this undergone?

**Comment by sprsquish** [comment]
Unit tests and I spun up the example on my system to check that the ZK announcer was working properly. More is coming, but I wanted to get this in front of eyes.

**Comment by bmdhacks** [comment]
I don't see the adaptive sampler in here.

**Comment by sprsquish** [comment]
It's not in here just yet. It's a complicated enough piece of code that I think it deserves a separate review anyway.

**Pull request closed without merging**
