### PR TITLE
BASH_SOURCE is a bashism, we should use bin/bash

### PR DESCRIPTION
**Pull request by baloo**
I did change the java call with an exec, shell should not lie around
once it did forward the args

Signed-off-by: Arthur Gautier baloo@gandi.net

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
don't mean to be bikesheddy, but do you strongly prefer /bin/bash vs /usr/bin/env bash?

http://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash

**Comment by baloo** [comment]
@adriancole fixed

**Comment by codefromthecrypt** [comment]
Thanks! can you rebase this and squash into a single commit? I'll merge after

**Comment by codefromthecrypt** [comment]
thx.. will get this through now!

**Comment by codefromthecrypt** [comment]
thanks so much!

closed via d09d50b8fb3cdb75f11bffc93825f472c8193791

**Pull request closed without merging**
