### PR TITLE
Prune the zipkin-browser-extension code from the core tree

### PR DESCRIPTION
**Pull request by rtyler**
The subtree history has been moved here:
    https://github.com/openzipkin/browser-extension

### CODE REVIEW

**Comment by michaelsembwever** [comment]
+1

On 16 July 2015 at 18:25, R. Tyler Croy notifications@github.com wrote:

> The subtree history has been moved here:
> 
> ## https://github.com/openzipkin/browser-extension
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/openzipkin/zipkin/pull/456
> Commit Summary
> - Prune the zipkin-browser-extension code from the core tree
> 
> File Changes
> - _D_ zipkin-browser-extension/firefox/CONTRIBUTING.md
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-0 (68)
> - _D_ zipkin-browser-extension/firefox/LICENSE.txt
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-1 (202)
> - _D_ zipkin-browser-extension/firefox/README.md
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-2 (37)
> - _D_ zipkin-browser-extension/firefox/ant.properties
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-3 (1)
> - _D_ zipkin-browser-extension/firefox/bootstrap.js
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-4 (141)
> - _D_ zipkin-browser-extension/firefox/build.xml
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-5 (60)
> - _D_ zipkin-browser-extension/firefox/chrome.manifest
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-6 (3)
> - _D_ zipkin-browser-extension/firefox/chrome/content/generateOutput.js
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-7 (158)
> - _D_ zipkin-browser-extension/firefox/chrome/content/getTraceId.js
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-8 (26)
> - _D_ zipkin-browser-extension/firefox/chrome/content/http.js
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-9 (40)
> - _D_ zipkin-browser-extension/firefox/chrome/content/log.js
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-10 (16)
> - _D_ zipkin-browser-extension/firefox/chrome/content/main.js
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-11 (116)
> - _D_ zipkin-browser-extension/firefox/chrome/content/mainOverlay.js
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-12 (9)
> - _D_ zipkin-browser-extension/firefox/chrome/content/mainOverlay.xul
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-13 (4)
> - _D_ zipkin-browser-extension/firefox/chrome/content/options.js
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-14 (88)
> - _D_ zipkin-browser-extension/firefox/chrome/content/options.xul
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-15 (6)
> - _D_ zipkin-browser-extension/firefox/chrome/content/timer.js
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-16 (41)
> - _D_ zipkin-browser-extension/firefox/chrome/content/traces.js
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-17 (78)
> - _D_ zipkin-browser-extension/firefox/chrome/content/translate.js
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-18 (9)
> - _D_ zipkin-browser-extension/firefox/chrome/content/zipkinModule.js
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-19 (30)
> - _D_ zipkin-browser-extension/firefox/chrome/content/zipkinPanel.js
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-20 (88)
> - _D_
>   zipkin-browser-extension/firefox/chrome/locale/en-US/zipkin.properties
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-21 (11)
> - _D_ zipkin-browser-extension/firefox/chrome/skin/classic/icon.png
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-22 (0)
> - _D_ zipkin-browser-extension/firefox/chrome/skin/classic/icon64.png
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-23 (0)
> - _D_ zipkin-browser-extension/firefox/chrome/skin/classic/loader.gif
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-24 (0)
> - _D_ zipkin-browser-extension/firefox/chrome/skin/classic/zipkin.css
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-25 (150)
> - _D_ zipkin-browser-extension/firefox/defaults/preferences/prefs.js
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-26 (6)
> - _D_ zipkin-browser-extension/firefox/install.rdf
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-27 (33)
> - _D_ zipkin-browser-extension/firefox/zipkin.xpi
>   https://github.com/openzipkin/zipkin/pull/456/files#diff-28 (0)
> 
> Patch Links:
> - https://github.com/openzipkin/zipkin/pull/456.patch
> - https://github.com/openzipkin/zipkin/pull/456.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openzipkin/zipkin/pull/456.

## 

Mick Semb Wever
Scandinavia

The Last Pickle
Apache Cassandra Consulting
http://www.thelastpickle.com

**Comment by codefromthecrypt** [comment]
:shipit:

**Comment by rtyler** [comment]
Travis is not yet green on master, so I'm just going to merge this with reckless abandon

**Comment by eirslett** [comment]
I suggest we use the firefox directory as root, and call this repo zipkin-firefox-extension (or something like that). I don't think this plugin will browser-agnostic anytime soon...

**Comment by codefromthecrypt** [comment]
@eirslett good point. sgtm

**Comment by eirslett** [comment]
Maybe even dig up the history since before sprsquish made that big-move-commit...

**Comment by rtyler** [comment]
@eirslett you're killin' me! mind just filing an issue on that repo to do that? :P

**Pull request merged**
