### PR TITLE
WIP moves to ASF zipkin-api removing google protobuf dep

### LINKED ISSUE #2550: I can't Build zipkin-Server it's always build failure
I use the command 
```
git clone https://github.com/openzipkin/zipkin
cd zipkin
./mvnw -DskipTests --also-make -pl zipkin-server clean install
```
then
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Zipkin (Parent) 2.13.0-SNAPSHOT:
[INFO]
[INFO] Zipkin (Parent) .................................... SUCCESS [02:30 min]
[INFO] Zipkin Core Library ................................ SUCCESS [ 46.815 s]
[INFO] Zipkin Interop Tests ............................... SUCCESS [  9.079 s]
[INFO] Zipkin UI .......................................... SUCCESS [01:14 min]
[INFO] Zipkin Lens ........................................ SUCCESS [01:10 min]
[INFO] Collector .......................................... SUCCESS [  0.612 s]
[INFO] Collector: Core Library ............................ SUCCESS [  1.685 s]
[INFO] Storage ............................................ SUCCESS [  0.563 s]
[INFO] Storage: Cassandra (Zipkin V2) ..................... SUCCESS [01:03 min]
[INFO] Storage: Cassandra (v1) ............................ SUCCESS [  5.553 s]
[INFO] Storage: Elasticsearch (V2) ........................ SUCCESS [ 16.455 s]
[INFO] Storage: MySQL (v1) ................................ SUCCESS [ 13.840 s]
[INFO] Collector: Kafka 0.10+ ............................. SUCCESS [01:04 min]
[INFO] Collector: RabbitMQ ................................ SUCCESS [ 19.452 s]
[INFO] Zipkin Server ...................................... FAILURE [04:53 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14:00 min
[INFO] Finished at: 2019-04-29T10:20:40+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.squareup.wire:wire-maven-plugin:3.0.0-alpha01:generate-sources (default) on project zipkin-server: Wire Plugin: Failure compiling proto sources.: google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field file (google/protobuf/descriptor.proto at 57:3)
[ERROR]   in message google.protobuf.FileDescriptorSet (google/protobuf/descriptor.proto at 56:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field message_type (google/protobuf/descriptor.proto at 74:3)
[ERROR]   in message google.protobuf.FileDescriptorProto (google/protobuf/descriptor.proto at 61:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field enum_type (google/protobuf/descriptor.proto at 75:3)
[ERROR]   in message google.protobuf.FileDescriptorProto (google/protobuf/descriptor.proto at 61:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field service (google/protobuf/descriptor.proto at 76:3)
[ERROR]   in message google.protobuf.FileDescriptorProto (google/protobuf/descriptor.proto at 61:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field extension (google/protobuf/descriptor.proto at 77:3)
[ERROR]   in message google.protobuf.FileDescriptorProto (google/protobuf/descriptor.proto at 61:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field options (google/protobuf/descriptor.proto at 79:3)
[ERROR]   in message google.protobuf.FileDescriptorProto (google/protobuf/descriptor.proto at 61:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field source_code_info (google/protobuf/descriptor.proto at 85:3)
[ERROR]   in message google.protobuf.FileDescriptorProto (google/protobuf/descriptor.proto at 61:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field field (google/protobuf/descriptor.proto at 96:3)
[ERROR]   in message google.protobuf.DescriptorProto (google/protobuf/descriptor.proto at 93:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field extension (google/protobuf/descriptor.proto at 97:3)
[ERROR]   in message google.protobuf.DescriptorProto (google/protobuf/descriptor.proto at 93:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field nested_type (google/protobuf/descriptor.proto at 99:3)
[ERROR]   in message google.protobuf.DescriptorProto (google/protobuf/descriptor.proto at 93:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field enum_type (google/protobuf/descriptor.proto at 100:3)
[ERROR]   in message google.protobuf.DescriptorProto (google/protobuf/descriptor.proto at 93:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field extension_range (google/protobuf/descriptor.proto at 108:3)
[ERROR]   in message google.protobuf.DescriptorProto (google/protobuf/descriptor.proto at 93:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field oneof_decl (google/protobuf/descriptor.proto at 110:3)
[ERROR]   in message google.protobuf.DescriptorProto (google/protobuf/descriptor.proto at 93:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field options (google/protobuf/descriptor.proto at 112:3)
[ERROR]   in message google.protobuf.DescriptorProto (google/protobuf/descriptor.proto at 93:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field reserved_range (google/protobuf/descriptor.proto at 121:3)
[ERROR]   in message google.protobuf.DescriptorProto (google/protobuf/descriptor.proto at 93:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field options (google/protobuf/descriptor.proto at 106:5)
[ERROR]   in message google.protobuf.DescriptorProto.ExtensionRange (google/protobuf/descriptor.proto at 102:3)
[ERROR]   in message google.protobuf.DescriptorProto (google/protobuf/descriptor.proto at 93:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field uninterpreted_option (google/protobuf/descriptor.proto at 129:3)
[ERROR]   in message google.protobuf.ExtensionRangeOptions (google/protobuf/descriptor.proto at 127:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field label (google/protobuf/descriptor.proto at 179:3)
[ERROR]   in message google.protobuf.FieldDescriptorProto (google/protobuf/descriptor.proto at 136:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field type (google/protobuf/descriptor.proto at 183:3)
[ERROR]   in message google.protobuf.FieldDescriptorProto (google/protobuf/descriptor.proto at 136:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field options (google/protobuf/descriptor.proto at 213:3)
[ERROR]   in message google.protobuf.FieldDescriptorProto (google/protobuf/descriptor.proto at 136:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field options (google/protobuf/descriptor.proto at 219:3)
[ERROR]   in message google.protobuf.OneofDescriptorProto (google/protobuf/descriptor.proto at 217:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field value (google/protobuf/descriptor.proto at 226:3)
[ERROR]   in message google.protobuf.EnumDescriptorProto (google/protobuf/descriptor.proto at 223:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field options (google/protobuf/descriptor.proto at 228:3)
[ERROR]   in message google.protobuf.EnumDescriptorProto (google/protobuf/descriptor.proto at 223:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field reserved_range (google/protobuf/descriptor.proto at 244:3)
[ERROR]   in message google.protobuf.EnumDescriptorProto (google/protobuf/descriptor.proto at 223:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field options (google/protobuf/descriptor.proto at 256:3)
[ERROR]   in message google.protobuf.EnumValueDescriptorProto (google/protobuf/descriptor.proto at 252:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field method (google/protobuf/descriptor.proto at 262:3)
[ERROR]   in message google.protobuf.ServiceDescriptorProto (google/protobuf/descriptor.proto at 260:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field options (google/protobuf/descriptor.proto at 264:3)
[ERROR]   in message google.protobuf.ServiceDescriptorProto (google/protobuf/descriptor.proto at 260:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field options (google/protobuf/descriptor.proto at 276:3)
[ERROR]   in message google.protobuf.MethodDescriptorProto (google/protobuf/descriptor.proto at 268:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field optimize_for (google/protobuf/descriptor.proto at 361:3)
[ERROR]   in message google.protobuf.FileOptions (google/protobuf/descriptor.proto at 318:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field uninterpreted_option (google/protobuf/descriptor.proto at 422:3)
[ERROR]   in message google.protobuf.FileOptions (google/protobuf/descriptor.proto at 318:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field uninterpreted_option (google/protobuf/descriptor.proto at 490:3)
[ERROR]   in message google.protobuf.MessageOptions (google/protobuf/descriptor.proto at 431:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field ctype (google/protobuf/descriptor.proto at 501:3)
[ERROR]   in message google.protobuf.FieldOptions (google/protobuf/descriptor.proto at 496:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field jstype (google/protobuf/descriptor.proto at 528:3)
[ERROR]   in message google.protobuf.FieldOptions (google/protobuf/descriptor.proto at 496:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field uninterpreted_option (google/protobuf/descriptor.proto at 581:3)
[ERROR]   in message google.protobuf.FieldOptions (google/protobuf/descriptor.proto at 496:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field uninterpreted_option (google/protobuf/descriptor.proto at 591:3)
[ERROR]   in message google.protobuf.OneofOptions (google/protobuf/descriptor.proto at 589:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field uninterpreted_option (google/protobuf/descriptor.proto at 612:3)
[ERROR]   in message google.protobuf.EnumOptions (google/protobuf/descriptor.proto at 597:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field uninterpreted_option (google/protobuf/descriptor.proto at 626:3)
[ERROR]   in message google.protobuf.EnumValueOptions (google/protobuf/descriptor.proto at 618:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field uninterpreted_option (google/protobuf/descriptor.proto at 646:3)
[ERROR]   in message google.protobuf.ServiceOptions (google/protobuf/descriptor.proto at 632:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field idempotency_level (google/protobuf/descriptor.proto at 673:3)
[ERROR]   in message google.protobuf.MethodOptions (google/protobuf/descriptor.proto at 652:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field uninterpreted_option (google/protobuf/descriptor.proto at 677:3)
[ERROR]   in message google.protobuf.MethodOptions (google/protobuf/descriptor.proto at 652:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field name (google/protobuf/descriptor.proto at 700:3)
[ERROR]   in message google.protobuf.UninterpretedOption (google/protobuf/descriptor.proto at 690:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field location (google/protobuf/descriptor.proto at 761:3)
[ERROR]   in message google.protobuf.SourceCodeInfo (google/protobuf/descriptor.proto at 717:1)
[ERROR] google/protobuf/descriptor.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field annotation (google/protobuf/descriptor.proto at 854:3)
[ERROR]   in message google.protobuf.GeneratedCodeInfo (google/protobuf/descriptor.proto at 851:1)
[ERROR] google\protobuf\compiler\plugin.proto needs to import google\protobuf\descriptor.proto
[ERROR]   for field proto_file (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\compiler\plugin.proto at 90:3)
[ERROR]   in message google.protobuf.compiler.CodeGeneratorRequest (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\compiler\plugin.proto at 67:1)
[ERROR] google\protobuf\type.proto needs to import google/protobuf/type.proto
[ERROR]   for field fields (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 51:3)
[ERROR]   in message google.protobuf.Type (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 47:1)
[ERROR] google\protobuf\type.proto needs to import google/protobuf/type.proto
[ERROR]   for field options (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 55:3)
[ERROR]   in message google.protobuf.Type (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 47:1)
[ERROR] google\protobuf\type.proto needs to import google/protobuf/type.proto
[ERROR]   for field syntax (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 59:3)
[ERROR]   in message google.protobuf.Type (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 47:1)
[ERROR] google\protobuf\type.proto needs to import google/protobuf/type.proto
[ERROR]   for field kind (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 119:3)
[ERROR]   in message google.protobuf.Field (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 63:1)
[ERROR] google\protobuf\type.proto needs to import google/protobuf/type.proto
[ERROR]   for field cardinality (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 121:3)
[ERROR]   in message google.protobuf.Field (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 63:1)
[ERROR] google\protobuf\type.proto needs to import google/protobuf/type.proto
[ERROR]   for field options (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 135:3)
[ERROR]   in message google.protobuf.Field (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 63:1)
[ERROR] google\protobuf\type.proto needs to import google/protobuf/type.proto
[ERROR]   for field enumvalue (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 147:3)
[ERROR]   in message google.protobuf.Enum (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 143:1)
[ERROR] google\protobuf\type.proto needs to import google/protobuf/type.proto
[ERROR]   for field options (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 149:3)
[ERROR]   in message google.protobuf.Enum (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 143:1)
[ERROR] google\protobuf\type.proto needs to import google/protobuf/type.proto
[ERROR]   for field syntax (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 153:3)
[ERROR]   in message google.protobuf.Enum (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 143:1)
[ERROR] google\protobuf\type.proto needs to import google/protobuf/type.proto
[ERROR]   for field options (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 163:3)
[ERROR]   in message google.protobuf.EnumValue (E:\workspace\zipkin\zipkin\zipkin-server\target\test\proto\google\protobuf\type.proto at 157:1)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :zipkin-server

```

### PR DESCRIPTION
**Pull request by codefromthecrypt**
We can merge this once the release vote is done and dusted cc @jeqo 

This will fix #2550 I think

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
@418545106 can you try building off this branch with windows?

**Comment by 418545106** [comment]
> @ 418545106你可以尝试用windows构建这个分支吗？

yes i can

**Comment by codefromthecrypt** [comment]
whoot! [zipkin committers] so less proto dependencies is good for windows, too :)

**Comment by niclash** [comment]
@adriancole Please don't use that @ address, since you have now notified some thousands of people of a meaningless comment (for most of us)

**Comment by codefromthecrypt** [comment]
@niclash OMG I am so embarassed. thanks for telling me

**Comment by codefromthecrypt** [comment]
I meant to @apache/zipkin-committers but goofed and the all one is the first in auto-complete. raising an issue with INFRA asking if there's ever a reason to notify the entire ASF with github

**Comment by codefromthecrypt** [comment]
@niclash I added an issue on this as eventhough it was my dumb fault it looks easy to do https://issues.apache.org/jira/browse/INFRA-18300

**Comment by andyjefferson** [comment]
Please you've been told already dont send this to everyone. Just stop.

⁣Sent from BlueMail ​

**Comment by codefromthecrypt** [comment]
closing this PR because notifications are pinned to the all committers list even when not directly mentioned apparantly.

**Pull request closed without merging**
