### PR TITLE
add version 9 to avoid the check with version 8

### PR DESCRIPTION
**Pull request by michael-wirth**

### CODE REVIEW

**Comment by michael-wirth** [comment]
https://github.com/openzipkin/zipkin/pull/3510 rebased as requested

**Comment by shakuzen** [comment]
Thank you for the pull request, but this still doesn't test that our code works with Elasticsearch 8, as I requested be added in https://github.com/openzipkin/zipkin/pull/3510#pullrequestreview-1297082145.

**Comment by fazilali** [comment]
can we get this merged?

**Comment by shakuzen** [comment]
> can we get this merged?

Not until [my review](https://github.com/openzipkin/zipkin/pull/3544#issuecomment-1603607673) is addressed.

**Comment by fazilali** [comment]
@shakuzen I have created another PR by addressing your review comment. can you take a look. https://github.com/openzipkin/zipkin/pull/3552

**Comment by shakuzen** [comment]
Closing in favor of https://github.com/openzipkin/zipkin/pull/3552

**Pull request closed without merging**
