### PR TITLE
Supports backfilling timestamp for one-way spans

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Before, we only supported backfilling timestamp and duration for spans
that have at least two annotations. This special cases an incomplete
one-way span (ex only cs), by adding its timestamp. This prevents the
UI from crashing.

See #1243

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
cc @dragontree101

**Comment by codefromthecrypt** [comment]
Sending one side separately from the other..
```bash
$ curl -s localhost:9411/api/v1/spans -H'Content-type: application/json' -d '[
  {
    "traceId": "77047bf9cf04ed5d",
    "id": "77047bf9cf04ed5d",
    "name": "get",
    "timestamp": 1484722951945904,
    "duration": 156470,
    "annotations": [
      {
        "timestamp": 1484722951945904,
        "value": "sr",
        "endpoint": {
          "serviceName": "client"
        }
      },
      {
        "timestamp": 1484722952102374,
        "value": "ss",
        "endpoint": {
          "serviceName": "client"
        }
      }
    ]
  },
  {
    "traceId": "77047bf9cf04ed5d",
    "id": "40ef4e93ab3b1507",
    "name": "get",
    "parentId": "77047bf9cf04ed5d",
    "annotations": [
      {
        "timestamp": 1484722952100852,
        "value": "cs",
        "endpoint": {
          "serviceName": "client"
        }
      }
    ]
  }
]'
$ curl -s localhost:9411/api/v1/spans -H'Content-type: application/json' -d '[
  {
    "traceId": "77047bf9cf04ed5d",
    "id": "40ef4e93ab3b1507",
    "parentId": "77047bf9cf04ed5d",
    "annotations": [
      {
        "timestamp": 1484722952121651,
        "value": "sr",
        "endpoint": {
          "serviceName": "server"
        }
      }
    ]
  },
  {
    "traceId": "77047bf9cf04ed5d",
    "id": "c8a3701afd819d33",
    "name": "process",
    "parentId": "40ef4e93ab3b1507",
    "timestamp": 1484722952121748,
    "duration": 656,
    "binaryAnnotations": [
      {
        "key": "lc",
        "value": "message-processor",
        "endpoint": {
          "serviceName": "server"
        }
      }
    ]
  }
]'
```

we get this due to backfilling of timestamp and duration of the middle one-way span
screen shot 2017-01-18 at 3 05 53 pm

**Comment by dragontree101** [comment]
now in zipkin-ui one-way is NaN?
image

**Comment by codefromthecrypt** [comment]
I can't see your example, but this change will likely fix the UI. That's
because the old duration logic did not expect a span with only "cs" and "sr"

**Comment by codefromthecrypt** [comment]
simplified code and updated description. key change here is making sure there's a timestamp added (which stops the UI from crashing)

**Comment by codefromthecrypt** [comment]
PS this is a screenshot of the in-flight span. duration absent appearing as NaN is a separate issue, which I'll raise separately.

screen shot 2017-01-18 at 8 03 46 pm

**Pull request merged**
