### PR TITLE
Scrooge updated to match plugin version

### PR DESCRIPTION
**Pull request by elbiczel**
When I tried running scrooge I got to an error:

```
[error] (zipkin-scrooge/*:update) sbt.ResolveException: download failed: com.twitter#scrooge-runtime_2.9.2;3.12.2!scrooge-runtime_2.9.2.jar(doc)
[error] download failed: com.twitter#scrooge-runtime_2.9.2;3.12.2!scrooge-runtime_2.9.2.pom
[error] download failed: com.twitter#scrooge-runtime_2.9.2;3.12.2!scrooge-runtime_2.9.2.jar(src)
```

Updating scrooge dependency version to 3.12.3, so that it matches scrooge-plugin version, resolved the issue.

### CODE REVIEW

**Comment by sprsquish** [comment]
We just released scrooge 3.13.0. Mind bumping to that?

**Comment by elbiczel** [comment]
Hi, @sprsquish. I tried doing so and I've run into a quite nasty problem. Running bin/web causes following StackOverflowError:

```
[info] Running com.twitter.zipkin.web.Main 
[error] java.lang.StackOverflowError
[error]     at scala.runtime.AbstractFunction0.<init>(AbstractFunction0.scala:12)
[error]     at scala.runtime.AbstractFunction0$mcV$sp.<init>(AbstractFunction0.scala:12)
[error]     at com.twitter.server.Closer$$anonfun$closeOnExit$1.<init>(Closer.scala:29)
[error]     at com.twitter.server.Closer$class.closeOnExit(Closer.scala:29)
[error]     at com.twitter.zipkin.web.Main$.closeOnExit(Main.scala:101)
[error]     at com.twitter.app.App$class.onExit(App.scala:87)
[error]     at com.twitter.zipkin.web.Main$.onExit(Main.scala:101)
[error]     at com.twitter.server.Closer$class.closeOnExit(Closer.scala:29)
[error]     at com.twitter.zipkin.web.Main$.closeOnExit(Main.scala:101)
[error]     at com.twitter.app.App$class.onExit(App.scala:87)
[error]     at com.twitter.zipkin.web.Main$.onExit(Main.scala:101)
```

Bumping plugin works fine, bumping scrooge library causes the error. I had a quick look at the source code and I think it is due to a bug in the new scrooge version.

**Comment by sprsquish** [comment]
Not sure why exactly. TwitterServer got an update, along with finagle and util. I just tried revving all of them and it ran.

These are the versions I used:
finagle: 3.13.1
util: 3.13.2
twitter-server: 1.6.1
scrooge: 3.13.0

**Comment by elbiczel** [comment]
That makes perfect sense. I've updated the pull request.

**Comment by sprsquish** [comment]
thanks!

**Pull request closed without merging**
