### PR TITLE
Update code to work with the latest versions of hbase and zookeeper

### PR DESCRIPTION
**Pull request by maz**

### CODE REVIEW

**Comment by suchang** [comment]
LGTM

**Comment by sprsquish** [comment]
When I try to run the tests for this `bin/sbt zipkin-hbase/test` I get the following:

```
[error] /Users/jeff/workspace/zipkin/oss/zipkin-hbase/src/test/scala/com/twitter/zipkin/storage/hbase/utils/HBaseSpecification.scala:4: HBaseTestingUtility is not a member of org.apache.hadoop.hbase
[error] import org.apache.hadoop.hbase.HBaseTestingUtility
[error]        ^
[error] /Users/jeff/workspace/zipkin/oss/zipkin-hbase/src/test/scala/com/twitter/zipkin/storage/hbase/utils/HBaseSpecification.scala:34: not found: type HBaseTestingUtility
[error]   lazy val sharedUtil = new HBaseTestingUtility()
[error]                             ^
[error] /Users/jeff/workspace/zipkin/oss/zipkin-hbase/src/test/scala/com/twitter/zipkin/storage/hbase/utils/HBaseSpecification.scala:11: not found: type HBaseTestingUtility
[error]   lazy val _util: HBaseTestingUtility = HBaseSpecification.sharedUtil
```

**Comment by maz** [comment]
That's another dependency problem. I think it should be fixed by

```
diff --git a/project/Project.scala b/project/Project.scala
index 61c2e9e..c5b2695 100644
--- a/project/Project.scala
+++ b/project/Project.scala
@@ -480,8 +480,10 @@ object Zipkin extends Build {
       "org.apache.hadoop"     % "hadoop-common"         % "2.4.0",
       "org.apache.hbase"      % "hbase"                 % hbaseVersion,
       "org.apache.hbase"      % "hbase-common"          % hbaseVersion,
+      "org.apache.hbase"      % "hbase-common"          % hbaseVersion % "test" classifier("tests") classifier(""),
       "org.apache.hbase"      % "hbase-client"          % hbaseVersion,
       "org.apache.hbase"      % "hbase-client"          % hbaseVersion % "test" classifier("tests") classifier(""),
+      "org.apache.hbase"      % "hbase-server"          % hbaseVersion % "test" classifier("tests") classifier(""),
       "com.google.guava"      % "guava-io"              % "r03" % "test",
       "com.google.protobuf"   % "protobuf-java"         % "2.4.1",
       "org.apache.hadoop"     % "hadoop-core"           % "1.2.1" notTransitive(),
```

I'm having trouble adding an additional resolver to get `hbase-common-0.98.3-hadoop2-tests.jar` since Typesafe doesn't have it in their repo. Once I've got the resolver working (and assuming that the dependency changes in the diff above solve the problem), I'll push a new commit with the changes.

**Comment by maz** [comment]
It appears that `com.twitter.common` requires Google guava version 16.  Hadoop's `org.apache.hadoop.util.JvmPauseMonitor` requires a lower version of guava: one which implements the `elapsedMillis()` method. I'm looking into a solution.

**Comment by maz** [comment]
For some reason, sbt is only trying the typesafe resolver, and is not trying the `DefaultMavenRepository` resolver as declared in `Project.scala`. Once the artifacts are resolved, the tests pass (at least on my machine). I'll continue trying to get the resolver working.

**Comment by sprsquish** [comment]
pulled internally. tests pass. thanks!

**Pull request closed without merging**
