### PR TITLE
refactor: Remove public visibility of JUnit 5 tests

### PR DESCRIPTION
**Pull request by timtebeek**
Another round of removing public modifiers from tests not needed anymore in JUnit JUpiter, after https://github.com/openzipkin/zipkin/pull/3630#issuecomment-1852999850.
This helps the public modifiers that are there for a reason stand out, and stops proliferation elsewhere.

Probably best to squash merge this one; had to revert some formatting changes.

### CODE REVIEW

**Comment by timtebeek** [comment]
There's also some common static analysis issues that [could be cleaned up](https://app.moderne.io/results/pCNYt89e6/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsIm9yaWdpbiI6ImdpdGh1Yi5jb20iLCJwYXRoIjoib3BlbnppcGtpbi96aXBraW4iLCJicmFuY2giOiJtYXN0ZXIifQ==?referrer=https%3A%2F%2Fapp.moderne.io%2Fresults%2FpCNYt89e6), but I was doubting if that's appreciated as it does switch some stylistic choices perhaps.

**Review by codefromthecrypt — APPROVED** [review]
Thanks yet again. We always squash on way in if multiple commits, so no problem there.

**Comment by timtebeek** [comment]
And of course if you'd want to run any of these same recipes against other openzipkin repositories I can facilitate that through the platform; just let me know and I can setup an OpenZipkin organization to select there.

**Comment by codefromthecrypt** [comment]
@timtebeek wrt OpenZipkin organization. Thanks, it would be helpful. Once we release 2.25.0 here we'll go to zipkin-reporter-java and do the same things notably off junit 4. Moderne is already proving a good decrufting tool, particularly as we are free to use offline and leave no side effects in the build.

**Comment by timtebeek** [comment]
Ah perfect, you can now select OpenZipkin from top left corner and run recipes against all of these repositories
image


Here's first run of JUnit Jupiter best practices against among others the zipkin-reporter-java that you mentioned:
https://app.moderne.io/results/YiPSV5epL

You can then follow up with the AssertJ best practices, Logging best practices and any other recipes you feel might improve the code there. Hope that helps!

**Comment by codefromthecrypt** [comment]
Thanks @timtebeek and just in time!

**Pull request merged**
