### PR TITLE
Documentation migrated to zipkin.io (repo openzipkin.github.io)

### PR DESCRIPTION
**Pull request by abesto**
1,971 deletions

### CODE REVIEW

**Comment by abesto** [comment]
Be advised, after this is merged, I'll also delete the `gh-pages` branch (it was built from content deleted in this PR)

**Comment by codefromthecrypt** [comment]
:shipit: thanks for the help!

**Comment by eirslett** [comment]
Looks like this might have broken the README.md file on Github...  I guess we could simply hotlink the images.

**Comment by abesto** [comment]
Ouch. I should've noticed that, sorry. Could hot-link, but that'll break in the far future and be even harder to notice. I'll pull that image back.

**Pull request merged**
