### PR TITLE
[WIP] Refactor global search component

### PR DESCRIPTION
**Pull request by tacigar**
Related: #2610 

**Work in progress**

### CODE REVIEW

**Comment by tacigar** [comment]
We use **React-Select** in GlobalSearch component.

React-select is a nice component library.
But, I think it is unsuitable for usage like GlobalSearch in the following points.

* In GlobalSearch, react-select's style needs to be modified a lot for design. I think it is not a beautiful way.
* As mentioned in #2485 , we want to display the dropdown menu more rich, but it seems impossible by using react-select.
* I want to control **focus** completely for providing more intuitive operation, but react-select black-boxes focus a bit...

So, I want to create a new **Select** component.

**Comment by tacigar** [comment]
I think now that we should use the desgin(CSS) Framework (related: #2451).
There are a lot of frameworks, but I want to use Material-UI (https://material-ui.com/) especially.
So I decided to introduce it within this GlobalSearch component at first in this PR.

**Comment by codefromthecrypt** [comment]
@tacigar I am sorry that the switch back to openzipkin will make this conflict a lot. If you want me to fix your branch and rebase I can. otherwise you will need to do this prior to merge.

Note: for license update, run: `./mvnw com.mycila:license-maven-plugin:format`

**Comment by tacigar** [comment]
OK!
Thank you for your information.
I'll update license myself 🙇

**Comment by tacigar** [comment]
Sorry, I'll close this PR and make an other PR.

**Pull request closed without merging**
