### PR TITLE
Improve MiniTimeline

### PR DESCRIPTION
**Pull request by tacigar**
Related #2503 

# have a threshold for when to use mini-map

**There is only1 spans -> not show mini timeline**

1span

**There are 2 ~ 14 spans -> mini timeline's height is 'num of spans × 5px'**

3 span

**There are more spans -> height is 75px**

more

# Add slider to improve UX

**Before**

before

**After**

after

### CODE REVIEW

**Comment by tacigar** [comment]
This PR is WIP yet, because I need to write unit tests.

**Comment by shakuzen** [comment]
Looks like all good improvements to me from looking at the screenshots. Great work!

**Review by codefromthecrypt — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
PS for messaging trace, there's often a long gap between producer and consumer. I always wondered if we could pinch the timeline together in cases like this...

**Comment by jcchavezs** [comment]
I love the way you care so much about details <3

ons. 24. apr. 2019, 04:05 skrev Adrian Cole <notifications@github.com>:

**Comment by tacigar** [comment]
PTAL 🙇

**Comment by codefromthecrypt** [comment]
are all the images still same?

**Comment by tacigar** [comment]
Yes
I just added unit tests

**Review by shakuzen — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
thanks very much!

**Pull request merged**
