### PR TITLE
Make hover effects in lens better

### PR DESCRIPTION
**Pull request by tacigar**
Make hover effects in lens better for better UX.

**BEFORE**

before-hover

**AFTER**

after-hover

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
So as I understand it, this makes what you are hovering over darker, so it is harder to lose your cursor? Am I missing anything else?

**Comment by tacigar** [comment]
That's all :)

**Review by codefromthecrypt — APPROVED** [review]
I agree this is helpful to see what you are doing

**Comment by codefromthecrypt** [comment]
thank you so much!

**Pull request merged**
