### PR TITLE
Adds messaging and database traces from Jorge 

### PR DESCRIPTION
**Pull request by zeagord**

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
only suggestion is to name the files also based on site. this helps folks know they are real, maybe answer questions later or link to site docs.

**Comment by zeagord** [comment]
Sure. Let me do that.

**Comment by codefromthecrypt** [comment]
he opted for no attribution, which is totally ok

**Comment by codefromthecrypt** [comment]
oops the first is in v1 format :) we should wash this through the server and re-add it.

(ex POST through the v1 endpoint, then GET via the v2 one)

**Pull request merged**
