### PR TITLE
Removes duplicate adaptive zookeeper sampler

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Collector used to have its own ZooKeeper sampler. This was written in
2012 and has been relatively untouched since. SpanStore introduced a
replacement, `zipkin-adaptive`, which is used inside twitter and can
be used by anyone caking up their collector `with AdaptiveSampler` and
 `override def spanStoreFilter = newAdaptiveSamplerFilter()`.

Removing the redundant implementation significantly reduces tech debt
and also a direct ZK dependency in `zipkin-collector-core`.

See #483

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
deploys fine internally at twitter

**Comment by abesto** [comment]
:+1: looks good. So much red!

**Comment by codefromthecrypt** [comment]
will merge on green. Thanks for having a look @abesto!

**Comment by eirslett** [comment]
Is zipkin the most continuously delivered product at Twitter now? :stuck_out_tongue_winking_eye:

**Comment by codefromthecrypt** [comment]
must be in the runnings :)

**Pull request merged**
