### PR TITLE
Revises info about Cassandra TTL

### PR DESCRIPTION
**Pull request by codefromthecrypt**
per chat with @pauldraper

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
@openzipkin/cassandra PS does anyone know how to adjust the TTL after the schema has been installed?

@pdraper tried this..

```bash
cqlsh> alter table zipkin.traces with default_time_to_live = 60480;
ServerError: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError
```

**Comment by codefromthecrypt** [comment]
@michaelsembwever ideas on changing the default ttl on an existing schema?

**Comment by codefromthecrypt** [comment]
opened another issue for how to modify ttl after the fact

**Comment by yurishkuro** [comment]
Curious as to the reasoning behind different TTLs

**Comment by codefromthecrypt** [comment]
This has been in place in some fashion since zipkin was around iirc. A
different ttl for data vs indexes supports retrieval by id for a longer
period without impacting the size or performance of search requests
(indexes). Runbooks in twitter had info go get trace by id when they were
in log files for example. This wouldnt need a search to work. Not sure if
this split is popular anymore though.

**Pull request merged**
