### PR TITLE
Add plugin function support to zipkin-tracer gem

### PR DESCRIPTION
**Pull request by Oscil8**
Also add support for rspec and write some tests.

### CODE REVIEW

**Comment by jamescway** [comment]
Do you guys think we could merge this branch?  I have some code based on this which allows the zipkin-tracer to use kafka.

**Comment by mosesn** [comment]
LGTM, but I don't know ruby very well.  @jamescway have you reviewed this code?  Does it look good to you?

**Comment by jamescway** [comment]
@mosesn yea LGTM :+1:

**Comment by codefromthecrypt** [comment]
If you can rebase this, happy to help merge it in!

**Comment by codefromthecrypt** [comment]
I'm going to try and get this merged, rebasing etc..

**Comment by codefromthecrypt** [comment]
closed via 13391db08f0e8ae581dcb86b80a629da3716959c

Thanks for the great work here.

**Pull request closed without merging**
