### PR TITLE
Add unit tests for TraceSummary component

### PR DESCRIPTION
**Pull request by tacigar**
**Before**

Before

**After**

After

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
test fail is due to timezone. if you have a way to lock timezone for test, use GMT

**Comment by tacigar** [comment]
I'll remove the test for now, because it is a bit hard for me to test formatted date...

**Comment by shakuzen** [comment]
> I'll remove the test for now, because it is a bit hard for me to test formatted date...

Do we want to open an issue to track testing this or is it not something we should test?

**Comment by codefromthecrypt** [comment]
even a TODO in the lines that would be covered by the test could help avoid
forgetting

**Comment by tacigar** [comment]
Sorry I added tests.

**Comment by codefromthecrypt** [comment]
thanks!

**Pull request merged**
