### PR TITLE
Add dependencies takeback button

### PR DESCRIPTION
**Pull request by t-yuki**
Add experimental takeback button to dependencies view.
It also depends on #920 because timestamp.js was not working.
Refs #791 #727

### CODE REVIEW

**Comment by t-yuki** [comment]
Is adding new interface acceptable?
Preview: 
image

**Comment by yurishkuro** [comment]
@t-yuki enhancing the interface is great! Only it's not clear to me what "take back" button means. Should it be just called "Run" or "Query" or "Execute"?

**Comment by t-yuki** [comment]
I changed the label to "Analyze Dependencies".
Also I added a missing file.
PTAL.

**Comment by codefromthecrypt** [comment]
Can you paste another image?

So the endTs and lookback is the same concept here as in the span query (main screen). Can you verify the fields are named the same and look similar? (for continuity's sake across the screens). Hard to tell, and they may already be.

I'm quite excited as I was interested in being able to see dependencies from a period besides yesterday.

I wouldn't necessarily say "analyze dependencies" as not all stores will do that online, but it is a minor point and I don't know a better word either!

@jcarres-mdsol @eirslett @kristofa any thoughts?

**Comment by t-yuki** [comment]
It queries to /dependency?endTs=1234&startTs but no effect for server side.
Instead, dependency.js converts `startTs` to `lookback` and sends a query with that parameter.
However, error cases like startTs > endTs is not handled well. (it ignores `startTs` simply)

I have no idea for wording of the button. Find traces page has `Find Traces` so I write `Analyze Dependencies` in Dependencies page. Also `Query` is nice.

Screens here:

image
image

**Comment by codefromthecrypt** [comment]
Thanks.

As far as I'm concerned, let's merge.

I did ping others, so will merge tomorrow unless feedback says otherwise.

**Comment by codefromthecrypt** [comment]
1.31.0 is on the way with this

**Pull request merged**
