### PR TITLE
Removes unimplemented RealtimeAggregates and supporting code

### PR DESCRIPTION
**Pull request by codefromthecrypt**

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
couldn't find any implementation that was not a no-op or throws an exception, not even at twitter.

**Comment by eirslett** [comment]
+1 sweet! Real time aggregates is still only a sweet dream, I'm afraid...

**Comment by spencergibb** [comment]
:+1:

**Comment by codefromthecrypt** [comment]
thanks for the look, folks

**Pull request merged**
