### PR TITLE
Dodges conflicts by removing explicit compass dep

### PR DESCRIPTION
**Pull request by codefromthecrypt**

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
tested manually on laptop by clearing all node related things and starting via bin/query, bin/web cc @yurishkuro @eirslett

**Comment by codefromthecrypt** [comment]
will test published snapshot to make sure packaging via travis still works.

**Comment by codefromthecrypt** [comment]
snapshot checks out ok

**Comment by yurishkuro** [comment]
thank you!

**Pull request merged**
