### PR TITLE
Adds the ability to log http requests sent to Elasticsearch

### PR DESCRIPTION
**Pull request by codefromthecrypt**
This is helpful when troubleshooting.

Ex.
```bash
STORAGE_TYPE=elasticsearch ES_HTTP_LOGGING=BASIC  java -jar ./zipkin-server/target/zipkin-server-*exec.jar
```

```
2017-05-15 23:05:10.600  INFO 78150 --- [alhost:9200/...] z.s.e.http.ElasticsearchHttpStorage      : --> GET http://localhost:9200/ http/1.1
2017-05-15 23:05:10.617  INFO 78150 --- [alhost:9200/...] z.s.e.http.ElasticsearchHttpStorage      : <-- 200 OK http://localhost:9200/ (16ms, unknown-length body)
2017-05-15 23:05:10.624  INFO 78150 --- [alhost:9200/...] z.s.e.http.ElasticsearchHttpStorage      : --> GET http://localhost:9200/_template/zipkin_template http/1.1
2017-05-15 23:05:10.626  INFO 78150 --- [alhost:9200/...] z.s.e.http.ElasticsearchHttpStorage      : <-- 200 OK http://localhost:9200/_template/zipkin_template (1ms, unknown-length body)
2017-05-15 23:05:10.635  INFO 78150 --- [alhost:9200/...] z.s.e.http.ElasticsearchHttpStorage      : --> POST http://localhost:9200/_bulk http/1.1 (1756-byte body)
2017-05-15 23:05:10.640  INFO 78150 --- [alhost:9200/...] z.s.e.http.ElasticsearchHttpStorage      : <-- 200 OK http://localhost:9200/_bulk (4ms, unknown-length body)
```

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
cc @openzipkin/elasticsearch @sirtyro I suspect y'all will find this super handy

**Comment by semyonslepov** [comment]
Wow, that should be superhelpful! We had some problems with AWS EC2 soon and were like blind kittens trying to understand what's going on. With this debug option it would be much easier.

**Comment by codefromthecrypt** [comment]
ps this was originally a desperate option to try and help debug #1594 glad it would be generally helpful!

**Comment by codefromthecrypt** [comment]
added env mapping will merge on green

**Pull request merged**
