### PR TITLE
Make configuring hbase client easier

### PR DESCRIPTION
**Pull request by elliottneilclark**
This make configuring hbase easier.  It also adds some docs about how to
configure hbase using hbase-site.xml

This also creates a script that helps automate creating hbase tables.

### CODE REVIEW

**Comment by elliottneilclark** [comment]
Failure seems un-related.  Seems like someone's maven repo was down.

**Comment by elliottneilclark** [comment]
I've got a newer version in a few mins.

**Comment by sprsquish** [comment]
Any update on this? :)

**Comment by codefromthecrypt** [comment]
feel free to open at some point. This looks helpful, but needs a rebase

**Pull request closed without merging**
