### PR TITLE
Change Download JSON button to be a normal link with href.

### LINKED ISSUE #3039: lens: hovering over [download json] button could show REST url to fetch trace
**Feature:**
When hovering over the download json button, it seems intuitive to show the full link to the trace (ie http://myhost/api/v2/trace/4f711e17e7e2290a) , in the browser status bar just as if you would hover over a normal href. 
 
**Rational**
I could not remember the location of the swagger api definition at https://zipkin.io/zipkin-api/ , i wanted to fetch a trace using curl | jq . So i looked at the download button hoping to find the REST url there.

### PR DESCRIPTION
**Pull request by anuraaga**
No need to create a magic anchor to do the download instead of making the original button an anchor.

Fixes #3039

### CODE REVIEW

**Comment by tacigar** [comment]
hmm...
I cannot download JSON in chrome (but I can in firefox)...

**Comment by anuraaga** [comment]
Ah I only checked on Firefox, let me check Chrome too

**Comment by anuraaga** [comment]
Just tried on Chrome and it worked ok - I do need to fix it to work on dev server using https://create-react-app.dev/docs/proxying-api-requests-in-development/#configuring-the-proxy-manually it only really works on normal server. Just to check, did you try using `:9411` or `:3000`?

**Comment by tacigar** [comment]
I tried using `:3000`.
`:9411` works ok.
The same problem seems to have existed before...

**Comment by anuraaga** [comment]
Thanks for confirming, yeah it broke in the dev server with the react-scripts migrations so will fix!

**Comment by anuraaga** [comment]
Fixed the proxy - went ahead and restored our API_BASE variable at the same time since it's easy

**Comment by jorgheymans** [comment]
maybe this is a good moment to have a deep and meaningful discussion about the placement of the button as well :-P

image

I'm thinking that it could make sense to have the download button next to the upload button instead, and make it an icon  only (with tooltip) so they're nicely uniform ? @tacigar also

**Comment by anuraaga** [comment]
I've been thinking the same thing - moving the button up seems good to me.

**Comment by anuraaga** [comment]
One point we'll need to think of is the other buttons. If we move download, we'd presumably move view logs and archive trace too. I'd say the icon for view logs is pretty bad - I desperately searched for something not terrible on font awesome. So icon-only might not be so nice. If we can get an icon designed that looks clearer that'd be very cool :D

**Comment by jorgheymans** [comment]
This may turn into a slightly bigger UI concept refactoring then, separate issue ? Thing is, there are 'global' widgets like the search trace and upload trace, then you have the trace 'local' stuff like download, view logs and archive. Is it ok mixing these into one "toolbar"?

**Comment by anuraaga** [comment]
Yup true that this would make the global toolbar dynamic - lots of code change as well as a big design change, so good to think about it separately.

**Comment by codefromthecrypt** [comment]
as we have some glitches in our last docker images, plus we've that favorite trace thing in master.. if this is good and mergable, let's do it and cut a minor?

**Pull request merged**
