### PR TITLE
add cassandra cql3 schema

### PR DESCRIPTION
**Pull request by jamescway**
#### Problem

The original cassandra schema was written in a deprecated
language (thrift), we need to switch to CQL3.
http://www.datastax.com/dev/blog/thrift-to-cql3

#### Solution

Update schema to use CQL3

#### Notes

* Replication uses 'SimpleStrategy'.  This is the minimum to get started.  More advanced deployments will want 'NetworkTopologyStrategy'
* @michaelsembwever suggested that we may update the value type to an alternate type 
  * DateTieredCompactionStrategy might be an alternative as well

### CODE REVIEW

**Comment by michaelsembwever** [comment]
+1

 i've been working on changes (for replacing cassie with datastax cql driver) off this.
it looks good.

**Comment by eirslett** [comment]
+1

We might also remove `AND COMPACT_STORAGE` later on, after migrating to the datastax driver?

**Comment by jamescway** [comment]
@michaelsembwever sounds awesome, @eirslett if I'm understanding you guys correctly we might change the  value field's type away from blob so we can use the other compaction strategy (date).

**Comment by michaelsembwever** [comment]
@jamescway yeah. i'm thinking this PR is the first step. Next step is replace cassie driver with datastax driver. Third step upgrade the schema to be transparent and date tiered compaction strategy friendly.

**Comment by adriancole** [comment]
cherry-picked into twitter/zipkin via https://github.com/twitter/zipkin/commit/7a4284d0c2dad0866b91e78cfbc190245e05a2c1

**Pull request merged**
