### PR TITLE
Host zipkin ui from query-service

### PR DESCRIPTION
**Pull request by eirslett**
We're getting closer!

### CODE REVIEW

**Comment by abesto** [comment]
There’s some special logic in `zipkin-web` to not trace static assets, may be worth porting here. See https://github.com/openzipkin/zipkin/blob/master/zipkin-web/src/main/scala/com/twitter/zipkin/web/FilteredHttpEntrypointTraceInitializer.scala and https://github.com/openzipkin/zipkin/blob/master/zipkin-web/src/main/scala/com/twitter/zipkin/web/Main.scala#L116-L121. (Not sure it applies, or applies directly)

**Comment by codefromthecrypt** [comment]
@abesto yeah that could be joined with FilteredHttpEntrypointTraceInitializer in zipkin-query

**Comment by codefromthecrypt** [comment]
works as advertised!

**Comment by codefromthecrypt** [comment]
FilteredHttpEntrypointTraceInitializer thing done.. merge on green!

**Pull request merged**
