### PR TITLE
Makes Lens default, removing the dependency on the classic UI

### PR DESCRIPTION
**Pull request by codefromthecrypt**
For well over a year, we've been working on Lens, most notably @tacigar.

A year ago we added the ability to transition to the new Lens UI: a
"Try Lens" button which resulted in a lot of addressed feedback,
much of it personally done by @tacigar. Even before that, we asked
others to contribute and while some tasks have happened, not all.

We can't be in perpetual transition, and Lens is a very good UI. By
removing the classic one, ideally those really concerned about the
remaining features can help to implement them. Meanwhile, we allow
Zipkin to live longer by stopping the large and self-imposed burden
that displaces the small amount of time we have.

I don't think everyone will be happy about this, but that doesn't mean
continue to do nothing except add work on ourselves either. For this
reason I think we should proceed and remove classic on the next
release even if some folks don't like that.

cc @openzipkin/core @openzipkin/ui

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
For context, one feedback we got last year from Haystack was that they too had a try button. So few people used it, that they had to pull the cord.

IMHO adding more "try" and "suggest" features is not an option anymore. We have to commit to the health of this project over a sense of perfection.

**Comment by jorgheymans** [comment]
Also those really infatuated with the classic UI always have the option to
stick to the previous version for a bit longer. +1 on making Lens default.

Op di 4 feb. 2020 04:49 schreef Adrian Cole <notifications@github.com>:

**Comment by codefromthecrypt** [comment]
also they can mount the web assets on a proxy and still benefit from the
core changes. remember the classic UI only uses the rest api and
config.json there's no buddy or anything.

**Review by basvanbeek — APPROVED** [review]
LGTM.

Happy to see the gaps also commented in code as TODO.

**Review by anuraaga — APPROVED** [review]
With some documentation about nginx + zipkin-classic in the release notes, seems like it's relatively safe.

**Comment by jcchavezs** [comment]
+1

**Review by shakuzen — APPROVED** [review]

**Review by tacigar — APPROVED** [review]
LGTM

**Review by huydx — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
FYI I offer to add documentation in release notes about nginx with classic. sure. still would be archived, which can formalize that we aren't doing security patch management on it, etc.

**Comment by anuraaga** [comment]
Ah I was expecting the release notes for this repo when updating - `zipkin-classic` doesn't need any more work other than archival

**Comment by eirslett** [comment]
LGTM! Cheers to the classic UI, it was fun while it lasted, long live Lens! 🍻 🍾 🎉

**Review by zeagord — APPROVED** [review]
It makes sense to retire Classic UI and makes Lens default. Less maintenance burden and Lens is also in a good shape now. We can add features based on requests and focus on that. I am good with this.

**Comment by codefromthecrypt** [comment]
merging due to unanimous consent!

**Comment by codefromthecrypt** [comment]
PS all the big ticket items listed here were later solved by @anuraaga!

* ZIPKIN_UI_BASEPATH for reverse proxy https://github.com/openzipkin/zipkin/issues/2519
* ZIPKIN_UI_LOGS_URL https://github.com/openzipkin/zipkin/issues/2491
* /config.json config overrides https://github.com/openzipkin/zipkin/issues/2969
* Chinese language support https://github.com/openzipkin/zipkin/issues/2970

**Pull request merged**
