### PR TITLE
Zipkin charts adding namespaces

### PR DESCRIPTION
**Pull request by mfordjody**
zipkin chart lack namespaces

### CODE REVIEW

**Review by jcchavezs — APPROVED** [review]

**Comment by jcchavezs** [comment]
Thanks @mfordjody. Could you check the error?

**Comment by mfordjody** [comment]
The reason for the version conflict, but I currently cannot see the ci status

**Comment by mfordjody** [comment]
Because the same version can cause conflicts, but I currently see the modification to version 0.7.0. I don't need to modify it again

**Comment by jcchavezs** [comment]
I think the issue is we should add a `version: x.x.x-snapshot` or disable version checking by using ` --check-version-increment=false`. Any input @jonkerj ?

**Comment by jonkerj** [comment]
It is very uncommon to template namespace from values, I'd recommend using `{{ .Release.Namespace }}` instead (which is very common practise). Any reason why you specifically want to sort of hardcode this from the values, @mfordjody?

As for the version/snapshot: if the chart version is CI'd during release, I'd agree with using snapshot/git refs for non-release, @jcchavezs.

**Comment by mfordjody** [comment]
> It is very uncommon to template namespace from values, I'd recommend using `{{ .Release.Namespace }}` instead (which is very common practise). Any reason why you specifically want to sort of hardcode this from the values, @mfordjody?
> 
> As for the version/snapshot: if the chart version is CI'd during release, I'd agree with using snapshot/git refs for non-release, @jcchavezs.

good idea

**Comment by jonkerj** [comment]
Much better. I would still personally prefer not using the define, and template `{{ .Release.Namespace }}` everywhere (it's what all major charts do), unless you really want to support the (IMO unlikely) scenario that the helm release lives in namespace A whereas the templated resources go into B. It may be a matter of taste, though. I'm a big fan of reducing complexity 😄

**Comment by codefromthecrypt** [comment]
this hasn't moved in half a year, so I added you to https://github.com/openzipkin/zipkin-helm so you can work with the others and make changes as needed directly. Later, we should remove the helm assets from here.

**Pull request closed without merging**
