### PR TITLE
Moves to Armeria with HttpTracing support

### PR DESCRIPTION
**Pull request by codefromthecrypt**
This is using Armeria 0.89 which has new tracing support from @kojilin https://github.com/line/armeria/pull/1906

The following is from self-tracing elasticsearch. 
Screenshot 2019-07-26 at 5 21 47 PM

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
To try:

```bash
TAG=new-armeria-tracer-SNAPSHOT
curl -sSL https://jitpack.io/com/github/openzipkin/zipkin/zipkin-server/${TAG}/zipkin-server-${TAG}-exec.jar > zipkin.jar
SELF_TRACING_ENABLED=true ES_HTTP_LOGGING=body STORAGE_TYPE=elasticsearch java -jar zipkin.jar
```

**Comment by trustin** [comment]
Thanks a log, @adriancole !

**Comment by codefromthecrypt** [comment]
ok this is ready cc @anuraaga @kojilin @trustin

**Review by trustin — APPROVED** [review]
Looking great, @adriancole :smile:

**Comment by codefromthecrypt** [comment]
the good looks are mostly @tacigar heh

**Pull request merged**
