### PR TITLE
Replace cassie with datastax cql driver

### PR DESCRIPTION
**Pull request by codefromthecrypt**
- remove all cassie classes
- remove Storage/Index/Aggregate classes. Zipkin now only supports the SpanStorage trait.
- remove the hadoop aggregation classes. (this needs to be rewritten from Cassie to using CqlInputFormat).
- introduce a new java "Repository" class that provides the persistence layer using the DataStax CQL driver.
- the Repository class sits in its own zipkin-cassandra-core subproject, a pure java dependency free artifact.
- the schema, found in cassandra-schema-cql3.txt, is automatically created during startup.
- minimal but incompatible changes to the schema as keyspace and table names are now all lowercase.
- comments have been added to cassandra-schema-cql3.txt as to how the datamodel can and should be improved.

ref: https://github.com/openzipkin/zipkin/issues/458

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
AFAICT, the only thing left is to make sure tests pass. If they don't, I'll update the PR so that they do!

cc @eirslett @michaelsembwever

**Comment by codefromthecrypt** [comment]
at least locally, this deflakes the test https://github.com/adriancole/zipkin/commit/ab2b69f8c4ce53d2eef91b168afe5a5b49f33abf

**Comment by codefromthecrypt** [comment]
updated with https://github.com/adriancole/zipkin/commit/7cf1880dc70f91f872fae11fa6776fe5ff622fe3 to honor cassandra dest

**Comment by eirslett** [comment]
Sweet!
A last, finishing touch; should we add a migration guide or changelog? Where the TLDR version is; wipe your old Cassandra keyspace and start from scratch?

**Comment by michaelsembwever** [comment]
it's going to start from scratch anyway. any migration guide needs to
- inform that existing data will be "lost" (in a now unused keyspace),
- "zipkin.store.cassie" flags have changed to "zipkin.store.cassandra", and most of them removed,
- we only support Cassandra-2.0+ (i suspect we still support C*-1.2 but it'll be nice to not say that)

**Comment by michaelsembwever** [comment]
i did a force push here to incorporate some small additions (i forgot to keep those commits separate like @adriancole did above, my bad)
- add CassandraSpanStoreFactory.createClusterBuilder() and added into the default implementation retryPolicy and loadBalancingPolicy,
- removed lots of unused or unneeded options,
- renamed all remaining flags to use the "zipkin.store.cassandra." prefix

**Comment by codefromthecrypt** [comment]
ok looks like all left is docs. I'm doing a rebase to see if it can go green

**Comment by michaelsembwever** [comment]
i've done a round with bin/collector|query|web|tracegen  and am happy with runtime.

**Comment by michaelsembwever** [comment]
anything other than README.md and CHANGELOG you'd like me to update?

**Comment by codefromthecrypt** [comment]
@michaelsembwever as far as I'm concerned :shipit:

**Comment by michaelsembwever** [comment]
can't actually see anything in README.md that's relevant.
just CHANGELOG, and there are we talking about changes for "1.2.1" ?

**Comment by codefromthecrypt** [comment]
@michaelsembwever yeah it is more about when we actually release 1.2.whatever. There's more to it than just cassandra.

**Comment by codefromthecrypt** [comment]
need a step here #579 iotw

**Comment by codefromthecrypt** [comment]
ok rebased for clean merge. just awaiting travis

**Comment by michaelsembwever** [comment]
Ok, then i would have added to CHANGES the following 

```
# 1.2.1
* Cassandra
  * Replaced internally cloned Cassie with the DataStax CQL driver
  * Change keyspace name from "Zipkin" to "zipkin"
  * Automatic schema creation on first start
```

but i let you do that in master or in #579

**Comment by codefromthecrypt** [comment]
FYI I'm stripping off the span store spec into a separate PR. The spec is entirely reliable on my machine, but something travis related is crashing it. Rather than thrash this PR, I'll spin it out and work on it independently.

**Pull request merged**
