### PR TITLE
Update Spring / Netty /Micrometer related dependencies

### PR DESCRIPTION
**Pull request by reta**
Update Spring / Netty /Micrometer related dependencies

### CODE REVIEW

**Review by codefromthecrypt — APPROVED** [review]
thx

**Comment by reta** [comment]
Huh, security is also happy now )

**Review by codefromthecrypt — APPROVED** [review]
cool we want the CVE report to be clean!

**Comment by ujo-trackunit** [comment]
Can you draft a new release with the fixes, please?

**Pull request merged**
