### PR TITLE
Add support for i18n and a few starting translated strings.

### PR DESCRIPTION
**Pull request by anuraaga**
This adds the infrastructure for being able to translate strings. Next will be the tedious part of replacing inline strings with formatted ones.

Note to frontend engineers, even when just prototyping, unless you are absolutely sure something won't ever be localized, strongly recommend using i18n from the start ;)

For #2970

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
@JoveYu @MrGlaucus @gzchenyong can you look at this for adding chinese support to lens UI?

**Review by codefromthecrypt — COMMENTED** [review]
Thanks for the start on this @anuraaga!

**Comment by jeqo** [comment]
Awesome! Next language could be español ;)

**Review by tacigar — APPROVED** [review]
LGTM! Awesome!

**Comment by jcchavezs** [comment]
or Catalonian cc @pchiwan @javigomez

man. 10. feb. 2020, 05:36 skrev Anuraag Agrawal <notifications@github.com>:

**Pull request merged**
