### PR TITLE
Removes freemarker.sourceforge.net repository reference

### LINKED ISSUE #469: Remove build dependency on source force repositories
Seeing a lot of these in recent builds:

```
[error] SERVER ERROR: Service Unavailable url=http://freemarker.sourceforge.net/maven2/org/codehaus/plexus/plexus/1.0.11/plexus-1.0.11.jar
[error] SERVER ERROR: Service Unavailable url=http://freemarker.sourceforge.net/maven2/org/slf4j/slf4j-parent/1.6.1/slf4j-parent-1.6.1.jar
[error] SERVER ERROR: Service Unavailable url=http://freemarker.sourceforge.net/maven2/org/eclipse/jetty/jetty-parent/18/jetty-parent-18.jar
[error] SERVER ERROR: Service Unavailable url=http://freemarker.sourceforge.net/maven2/org/eclipse/jetty/orbit/jetty-orbit/1/jetty-orbit-1.jar
```

Connectivity issues aside, Source forge distributes [malware](http://arstechnica.com/information-technology/2015/05/sourceforge-grabs-gimp-for-windows-account-wraps-installer-in-bundle-pushing-adware/) and is a pretty crap player nowadays.

### PR DESCRIPTION
**Pull request by codefromthecrypt**
freemarker.sourceforge.net causes build problems, and isn't needed
anyway. This removes it and ensures the old example that declared it
still compiles.

Closes #469

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
Tested by building the example.

``` bash
$ cat ~/.sbt/0.13/global.sbt
publishTo := Some(Resolver.file("file",  new File(Path.userHome.absolutePath+"/.m2/repository")))
$ sbt publish
$ cd doc/examples/collector
$ sbt clean test
```

**Comment by codefromthecrypt** [comment]
build failures are unrelated

**Comment by codefromthecrypt** [comment]
I'm going to rebase this and see if anything helped.

**Comment by jamescway** [comment]
:+1: not really expecting the built to succeed

**Pull request merged**
