### PR TITLE
Add support for specifying a trusted cert via env

### PR DESCRIPTION
**Pull request by jroes**
This adds support for specifying a trusted cert via an environment variable.

This may not be quite up to standard, but wanted to start a conversation and confirm that there was interest in merging this support into the mainline before pursuing hygienic improvements.

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
thanks for opening up the topic for conversation. good start and helpful.

So, at the component abstraction, we don't use anything that binds environment variables, as configuration can vary wildly depending on the framework used. Firstly, I'm curious if things "just work" if the java system provided trust store is present.. ex. `-Djavax.net.ssl.trustStore`

If not, we'd want to do the following:
- identify the surface area we need for SSL configuration needed
- figure out how to make it possible to configure
  - ex via a direct option, or exposing or accepting a Cluster.Builder

cc @openzipkin/cassandra

**Comment by codefromthecrypt** [comment]
@michaelsembwever any thoughts on this? do you know if the default trust store works, or if configuration here is inevitable for TLS client auth

**Comment by ys** [comment]
I have the feeling that looking at the driver, the `withSSL` part is inevitable for cassandra. 
With that part, I think that using the default keystore by be enough... but would be rad to have a basic support with just the `withSSL` merged already so that we can try it.

Nobody ever thought about using encrypted communication between server and Cassandra?

**Comment by ys** [comment]
According to the docs https://datastax.github.io/java-driver/manual/ssl/#jsse-property-based it should work

**Comment by michaelsembwever** [comment]
Can we close this in favour of https://github.com/openzipkin/zipkin/pull/1401 ?

**Comment by codefromthecrypt** [comment]
I think most are interested in the other PR. Let's go with that for now! Thanks for starting the gears turning, @jroes

**Pull request closed without merging**
