### PR TITLE
Publish using CircleCI

### PR DESCRIPTION
**Pull request by abesto**
# DO NOT MERGE YET

Continuing the work in #1248, this PR is the place to discuss whether, when, and how we want to move releasing from Travis to CircleCI.

_openzipkin/zipkin on CircleCI_: https://circleci.com/gh/openzipkin/zipkin

Why: https://github.com/openzipkin/zipkin/issues/1237
## Things to consider before merging
- Do we like the trade-off CircleCI makes in terms of build executors? OSS orgs (NOT repos) get a total of 4 containers, meaning we can do 4 things at the same time. At the moment `openzipkin/zipkin` is configured to use all 4 containers for running tests in parallel, but over time we may want to have concurrent builds of separate commits / branches. PRs also run on the same pool of containers, as well as any other `openzipkin` projects we may migrate to CircleCI in the future. OTOH we can pay monies for more containers, unlike with Travis (citation needed).
- Do we want to spend extra effort on doing a test-run of the deployment process on "non-production" Bintray / Maven repos?
- Are we really comfortable jumping onto CircleCI? Maybe run a dual setup for a while and learn by doing.
## Things to do before merging
- Review! ;)
- Add credentials to CircleCI, in one of two ways:
  - Via the web UI: https://circleci.com/docs/environment-variables/#setting-environment-variables-for-all-commands-without-adding-them-to-git
  - Encrypted in `circle.yml`, tooling more rudimentary than in Travis: https://github.com/circleci/encrypted-files
- Disable builds on Travis to avoid confusion when they both want to upload to Bintray
- Enable "GitHub Status updates" on https://circleci.com/gh/openzipkin/zipkin/edit#advanced-settings
- Replace build badge in `README.md` (https://circleci.com/gh/openzipkin/zipkin/edit#badges)

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
fyi just had a zombie build today. even with nothing else in the org running, the below job hung for >15m waiting to be scheduled https://circleci.com/gh/openzipkin/zipkin/347

so far seems canceling and retrying works. Only mentioning here as it seems that this topic comes up sometimes https://discuss.circleci.com/t/indefinitely-queued-build/1584/33

**Comment by codefromthecrypt** [comment]
PS circleci has been extremely flakey, moreso than travis who is doing more work (ex running docker tests). There's a rumor that circle 2.0 might make things less flakey. I'd recommend we continue to not push for more things on circle until at least normal builds pass routinely

**Comment by flipdiving** [comment]
What do you like best?
So far circleci has been following our company in everything we do. We based all our workflow around CI, there have been downtimes, there have been small technical issues to overcome - but in general, circleci has took a huge load out of our shoulders. Support has been provided by engineers, company is striving to improve it's product and doesn't stop on what they achieved. Thei CircleCI 2.0 version seems very promising already (and it's only Beta).

What do you dislike?
There are no major issues i can remember - we had some problems with environment variables not being stable to rely on. During platform switch some components have been turn-off by default and took a while to figure out. All those have been solved.

What business problems are you solving with the product? What benefits have you realized?
CircleCi has been an essential tool to improve quality of our products. We've been heavily reliant on automating everything we can - from testing, to code review to automated code analysis. We also managed to remove human factor from platform deployment and we gave away this responsibility to CircleCI.
[colour switch](http://colour-switch.com)

**Comment by codefromthecrypt** [comment]
closing as very over year old :)

**Pull request closed without merging**
