### PR TITLE
Backfills UI tests for annotation and binary annotation value formatting

### PR DESCRIPTION
**Pull request by codefromthecrypt**
See #1458

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
screen shot 2017-01-06 at 2 37 50 pm

cc @jakubhava @cburroughs @eirslett

**Comment by jakubhava** [comment]
Cool, thanks a lot @adriancole ! I was trying to find something really complicated in writing these tests, but this is easy and great!

**Comment by eirslett** [comment]
Nice! :shipit:

**Comment by codefromthecrypt** [comment]
@jakubhava no problemo. I learned this stuff from @eirslett, and now the virus spreads to you :)

**Pull request merged**
