### PR TITLE
Add support for JavaScript unit tets

### PR DESCRIPTION
**Pull request by eirslett**
Use karma as a test runner, mocha/chai as
the test framework, and run tests in
PhantomJS.

### CODE REVIEW

**Comment by eirslett** [comment]
@abesto the node/npm/webpack/karma stuff slows down the build quite a lot. Could you please help out with some gradle magic to improve the build time? Incremental builds etc.?

**Comment by codefromthecrypt** [comment]
last build before this was 6s faster, but most recent ones are 30s faster than this.

**Comment by abesto** [comment]
Sure, sounds fun. The next few days look kinda chaotic, no promises on the timeline.

**Comment by codefromthecrypt** [comment]
thinking we merge this to encourage test writing... I'm personally not deterred by the build time creep.

**Comment by eirslett** [comment]
:-)

I'm also working on top of this patch to add unit tests while rewriting logic from Scala to JavaScript.
Eventually, I think the zipkin-web submodule will be packaged as a tar.gz or zip artifact, and then imported as a gradle dependency into zipkin-query and zipkin-java. (Which is a consideration when thinking about optimizing the build)

**Comment by codefromthecrypt** [comment]
Ok so cool to merge this, of do you want to add more to it?

**Comment by eirslett** [comment]
I'm good.

**Pull request merged**
