### PR TITLE
Add support for elasticsearch 8 (es 8) by adding checkings with version 9

### PR DESCRIPTION
**Pull request by lmarkusl**
add version 9 to avoid the check with version 8

### CODE REVIEW

**Comment by lmarkusl** [comment]
PR from issue https://github.com/openzipkin/zipkin/issues/3468

**Review by shakuzen — CHANGES_REQUESTED** [review]
Thanks for the pull request. We want to test that what we say works actually works. We have existing Elasticsearch integration tests. Could you copy from e.g. `ITElasticsearchStorageV7` to make one for ES 8?

**Review by sergiochoo — APPROVED** [review]
lgtm

**Comment by shakuzen** [comment]
This is still missing tests for the version of Elasticsearch this change claims we support. We need to add that before we can merge this.

**Comment by jcchavezs** [comment]
Please rebase

**Comment by longnnit** [comment]
Please rebase

**Comment by fazilali** [comment]
can we get this merged

**Comment by shakuzen** [comment]
Closing in favor of https://github.com/openzipkin/zipkin/pull/3552

**Pull request closed without merging**
