### PR TITLE
Adds elasticsearch6 and elasticsearch7 images

### PR DESCRIPTION
**Pull request by codefromthecrypt**
These are used in our integration tests for zipkin-storage/elasticsearch

See https://github.com/openzipkin/docker-zipkin/issues/86

Tested with
```bash
$ cd docker
$ DOCKERFILE_PATH=docker/Dockerfile DOCKER_TAG=foo hooks/post_build
```

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
verified all the things

**Comment by anuraaga** [comment]
Does this mean when we attic `docker-zipkin` elasticsearch2 and 5 will stop being updated forever? Makes sense to me just want to confirm.

**Comment by codefromthecrypt** [comment]
yep let them die

**Comment by codefromthecrypt** [comment]
I'm only adding in images we use or suggest for testing. we no longer reference 2 and 5 in our integration tests, which is the longer rationale.

we should bring the instructive docker-compose files over, including the prometheus demo, but yeah the old ES images can die

**Pull request merged**
