### PR TITLE
Adds UI test data for SmartThings OAuth Authorization flow.

### PR DESCRIPTION
**Pull request by llinder**

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
I see nothing! ps when you submit can you change to v2 format? easy way is to post local to v1 endpoint then GET on the v2

**Comment by llinder** [comment]
Ha guess it would help if I saved the file before making the pull request!

**Comment by codefromthecrypt** [comment]
thanks tons lance!

**Comment by codefromthecrypt** [comment]
context was @kellabyte was asking about a sample. Here's the chat description from gitter:

> To describe it in a few sentences… we add trace propegation across web redirects to tie several systems together, especially when they involve round trips to other web sites we don’t own. Further we add user IDs to these traces to investigate specific customer issues or complaints. Lastly we also embed the trace context in things like oauth authorization codes so we can tie a full user actions together even when part of that action is performed on backend systems we don’t own.

**Pull request merged**
