### PR TITLE
change the default address/port to connect to the query server

### PR DESCRIPTION
**Pull request by bmdhacks**

### CODE REVIEW

**Comment by johanoskarsson** [comment]
Seems to have broken the build. Do the tests pass locally for you?

**Comment by bmdhacks** [comment]
They mostly pass for me.  I don't have redis or Zookeeper on my system so that causes a lot of errors.  Let me dig down and see what I can do to fix this.

**Comment by franklinhu** [comment]
Yeah the integration test is flaky :frowning:

**Comment by johanoskarsson** [comment]
+1

**Comment by franklinhu** [comment]
+1

**Pull request merged**
