### PR TITLE
Bump Mockito to version 2.22.0

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
thanks.. in the future, can you please bundle together incidental versions? It helps keep the commit log readable and concise. Usually we do a round at one time especially with things like build/test deps.

I'll merge this provided there aren't others to follow.. if that's the case, please put them in this branch and I'll squash them.

**Comment by oscerd** [comment]
@adriancole sure, I noticed Mockito version after the first PR. Sorry for the mess.

**Comment by codefromthecrypt** [comment]
wasn't sure if it was intentional or not. all good!

**Comment by oscerd** [comment]
CircleCI is still failing but it doesn't seem to be related to the PR.

**Comment by codefromthecrypt** [comment]
agreed not related. thanks!

**Pull request merged**
