### PR TITLE
Do npm audit fix in lens

### PR DESCRIPTION
**Pull request by tacigar**
When I do `npm install` in lens directory, a severity vulnerability was found.

```
                       === npm audit security report ===                                      
                                                                                              
# Run  npm install --save-dev webpack-dev-server@3.1.14  to resolve 1 vulnerability           
┌───────────────┬──────────────────────────────────────────────────────────────┐              
│ High          │ Missing Origin Validation                                    │              
├───────────────┼──────────────────────────────────────────────────────────────┤              
│ Package       │ webpack-dev-server                                           │              
├───────────────┼──────────────────────────────────────────────────────────────┤              
│ Dependency of │ webpack-dev-server [dev]                                     │              
├───────────────┼──────────────────────────────────────────────────────────────┤              
│ Path          │ webpack-dev-server                                           │              
├───────────────┼──────────────────────────────────────────────────────────────┤              
│ More info     │ https://nodesecurity.io/advisories/725                       │              
└───────────────┴──────────────────────────────────────────────────────────────┘ 
```

So I do `npm audit fix`.

### CODE REVIEW

**Review by shakuzen — APPROVED** [review]
Thanks. We also get a vulnerability alert with the current ui (in `/zipkin-ui`). Is it worth fixing there also?

**Comment by tacigar** [comment]
The same warning (about webpack-dev-server) occurs in `zipkin-ui`, so it is easy to fix.
I'll fix it in this PR.

**Comment by tacigar** [comment]
Oh... `webpack-dev-server` used by `zipkin-ui` is too old...

I think that we have to be a bit cautious about this matter.
I said that I fix it in this PR, but I will give up...
I'll make other PR for this.

**Comment by codefromthecrypt** [comment]
thanks for the chore!

**Pull request merged**
