### PR TITLE
feat: adding es auth environment vars

### PR DESCRIPTION
**Pull request by erbrjr**
Adding Elasticsearch Authentication environment variables.

### CODE REVIEW

**Comment by jonkerj** [comment]
I've submitted #3434 a while ago, which could cover your use case too. It seems kind of hard to get someone to look at it, so let's make some noise 😄 

EDIT: there is also #3446, which does more or less the same. But it is getting the same amount of love as the other helm PRs

**Comment by jcchavezs** [comment]
Please rebase @erbrjr

**Comment by jcchavezs** [comment]
@jonkerj I think having specific fields for env in ES looks more appealing rather than ingesting whatever env var. Could you maybe clarify the env vars you are expecting to send?

**Comment by jonkerj** [comment]
That's OK with me. Looking at this PR, it would involve `ES_USERNAME`, `ES_PASSWORD` and `ES_SSL_NO_VERIFY`.

The PR looks good to me, btw (after a rebase, probably).

**Review by jcchavezs — APPROVED** [review]

**Pull request merged**
