### PR TITLE
Updates to gradle 2.13

### PR DESCRIPTION
**Pull request by codefromthecrypt**

### CODE REVIEW

**Comment by yurishkuro** [comment]
lgtm

any particular new feature you are after?

**Comment by codefromthecrypt** [comment]
Sorry I should have mentioned. Mainly this is maintenance, ie not falling
too far behind. Also there's supposedly a performance improvement. I'll
check logs to see if that helped at all.

**Comment by codefromthecrypt** [comment]
performance has been erradic in general, so this might not change things on that note.

**Comment by codefromthecrypt** [comment]
reverting this. Even with latest idea, the project no longer imports properly. will rev-lock for now.

**Pull request merged**
