### PR TITLE
Make collapse button work by default

### PR DESCRIPTION
**Pull request by naoman**
This simple change works for me. Maintainers, feel free to make edits. #1774

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
thanks. needs a unit test (made mention in the corresponding issue a while back, basically we should have some data to drive this)

**Comment by codefromthecrypt** [comment]
this needs analysis @zeagord @tacigar ?

**Comment by zeagord** [comment]
> this needs analysis @zeagord @tacigar ?

Yes, It doesn't work. Let me look in to it

**Comment by codefromthecrypt** [comment]
this has been obviated by a UI rewrite :)

**Pull request closed without merging**
