### PR TITLE
Adds trace IDs to dependency links

### PR DESCRIPTION
**Pull request by codefromthecrypt**
TODO: make this conditional, as existing dependency linker jobs won't
need IDs and keeping them might make spark jobs move more data than
they currently need.

See #1206

### CODE REVIEW

**Review by zeagord — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
ps not merging intentionally until we get some experience with the
experiment. reason is that this is api breaking

**Comment by codefromthecrypt** [comment]
for those wondering.. pausing while we investigate what else is out there (ex haystack has some aggregation tools as well.. not sure if there is any overlap until we ask)

**Comment by codefromthecrypt** [comment]
I think we can pick this back up in javascript after #2731

**Comment by codefromthecrypt** [comment]
moved most code out in this https://github.com/openzipkin/zipkin/pull/2803

**Comment by codefromthecrypt** [comment]
moved to branch attic/links-with-traceIds

**Pull request closed without merging**
