### PR TITLE
Revert "Adds the gitter link in the question sumary"

### PR DESCRIPTION
**Pull request by jcchavezs**
Reverts openzipkin/zipkin#2250

Ping @beckje01 @adriancole

### CODE REVIEW

**Review by drolando — APPROVED** [review]

**Comment by drolando** [comment]
What about just adding the url for gitter? Would that fit?

**Comment by codefromthecrypt** [comment]
added a commit for plain links

**Comment by drolando** [comment]
That string is still more than 200 chars...

```python
>>> len("This issue tracker is not the place for questions. If you want to ask how to do something, or to understand why something isn't working the way you expect it to, please use https://gitter.im/openzipkin/zipkin or https://stackoverflow.com/questions/tagged/zipkin.")
262
```

**Comment by codefromthecrypt** [comment]
maybe we just give gitter link then..

**Comment by codefromthecrypt** [comment]
thanks for the watchdog service @beckje01 @drolando!

**Comment by beckje01** [comment]
Looks good now

**Pull request merged**
