### PR TITLE
Updates all the things in preparation for a release

### PR DESCRIPTION
**Pull request by codefromthecrypt**
* uses a more recent zipkin-ui (classic) which works around a 404
* updates to latest spring boot
* updates to latest maven
* latest errorprone has a bug and so we disable the check ExtendsAutoValue

### CODE REVIEW

**Review by anuraaga — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
hmm google's cache is waaaaaaay behind

https://maven-central.storage-download.googleapis.com/repos/central/data/com/github/eirslett/frontend-maven-plugin/1.9.1/frontend-maven-plugin-1.9.1.pom is 404

https://repo1.maven.org/maven2/com/github/eirslett/frontend-maven-plugin/1.9.1/frontend-maven-plugin-1.9.1.pom was published over 2 weeks ago! cc @eirslett

**Comment by codefromthecrypt** [comment]
1.9.0 is available.. tempted to use it until google thing is ok again

**Comment by anuraaga** [comment]
I'd suggest either using jcenter or just normal https://repo1.maven.org/maven2/, I think even maven central is using Fastly now adays so is pretty fast

**Comment by codefromthecrypt** [comment]
we don't explicitly use google's mirror I think this is travis..

**Comment by anuraaga** [comment]
Oh boo...

**Comment by codefromthecrypt** [comment]
we can re-add the default I guess https://travis-ci.community/t/disable-google-maven-central/5301/3

**Comment by codefromthecrypt** [comment]
re-kicking build (clean cache) as even spring boot wasn't resolving

**Comment by codefromthecrypt** [comment]
ok lost patience. I (hopefully) obviated the google mirror

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/2964 might obviate the obviation, we'll see!

**Comment by codefromthecrypt** [comment]
travis cache was ultimately the problem, as it cached a ref to a basepath no longer synced. I thought I nuked the travis cache, but apparently didn't

**Pull request merged**
