### PR TITLE
Moves zipkin-mongodb to its own repository

### PR DESCRIPTION
**Pull request by codefromthecrypt**
zipkin-mongodb was late merged and has little test coverage. The tests
that do run require special travis or laptop configuration to manage a
localhost mongod. The maintenance involved in mongod is not justifiable,
as it isn't likely used by anyone.

This change isolates mongodb to its own repository, where it can either
be maintained, or be archived.

It is an acknowledged reality that this repository won't work until we
release zipkin artifacts it depends on, and perhaps perform other
modularity work.

https://github.com/openzipkin/zipkin-mongodb

Commands used to make zipkin-mongodb

``` bash
git clone https://github.com/openzipkin/zipkin.git
cd zipkin/
git subtree split -P zipkin-mongodb -b zipkin-mongodb
git checkout zipkin-mongodb
git remote add zipkin-mongodb https://github.com/openzipkin/zipkin-mongodb.git
git push -f zipkin-mongodb zipkin-mongodb:master
```

### CODE REVIEW

**Comment by abesto** [comment]
The implementation looks fine to me. Maybe add some context on why this is happening?

**Comment by codefromthecrypt** [comment]
Ahh sure. The context is that mongo was a very late merged change. So late, that it is not likely used. Mongo requires a special build (to enable the mongodb service or run locally), and has very little test coverage. Moving this out is reflection that it needs a lot of work, or possible archive.

**Comment by jamescway** [comment]
:star: :+1: :star:

**Comment by abesto** [comment]
:shipit: :rainbow:

**Comment by codefromthecrypt** [comment]
fixed commit message to include rationale.

**Pull request merged**
