### PR TITLE
Reuse search bar in dependencies page

### LINKED ISSUE #2475: Add dependencies analyze button to search bar
To reuse search bar, I want to add dependencies analyze button to search bar and move the current search button like the following.

new

@adriancole What do you think?

### PR DESCRIPTION
**Pull request by tacigar**
Related Issue: #2475 

What I did in this PR are the following.

* Unite trace-search page and dependency page as Discover page, which is tab-based page.
* Update react-router for uniting multiple path to one component. **← This makes this PR large**.
* Remove unused files.

The reason I used Tab is because I thought that the most natural way for users to use GlobalSearch for searching Dependencies.

fixes: #2475

### CODE REVIEW

**Comment by tacigar** [comment]
Current state:




I added DiscoverPage and added tabs to it.

**Comment by codefromthecrypt** [comment]
lint is a little sad. I can add a commit to make it more happy

```
[INFO] > zipkin-lens@0.0.1 lint /home/travis/build/openzipkin/zipkin/zipkin-lens
[INFO] > eslint src
[INFO] 
[INFO] 
[INFO] /home/travis/build/openzipkin/zipkin/zipkin-lens/src/components/DiscoverPage/api.test.js
[INFO]   15:3  error  buildTracesQueryParameters not found in './api'  import/named
[INFO] 
[INFO] /home/travis/build/openzipkin/zipkin/zipkin-lens/src/hooks/useUnmount.js
[INFO]   16:50  warning  React Hook useEffect has a missing dependency: 'f'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
[INFO] 
```

**Comment by codefromthecrypt** [comment]
fixed lint but unsure if the test failure is drift or legit, so will pause

**Comment by codefromthecrypt** [comment]
very looking forward to this @tacigar!

**Comment by tacigar** [comment]
Please try to use 🙇

**Comment by tacigar** [comment]
Sorry...The change has been large due to updating packages...

**Comment by tacigar** [comment]
GIF

reuse-searchbar

**Comment by codefromthecrypt** [comment]
checking now thanks!

**Comment by tacigar** [comment]
What I will do after this PR is the improvement of trace-search page design.
Related to #2636

**Review by codefromthecrypt — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
very good job. I tried locally and smooth!

**Comment by tacigar** [comment]
Thank you!

**Pull request merged**
