### PR TITLE
Updates to latest Finagle deps

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Synchronizes the dependency graph per recently released Finagle.
Following this, we can start scala 2.11 work.

https://groups.google.com/forum/#!topic/finaglers/nS2DqTYftdY

### CODE REVIEW

**Comment by abesto** [comment]
Builds fine locally, looks good to me. :shipit:

**Comment by codefromthecrypt** [comment]
travis is normal (one JRE passes, other is killed due to megabuild)

**Comment by eirslett** [comment]
+1
Maybe Scala 2.11 makes the build faster?

**Comment by jamescway** [comment]
:+1:  I guess I'll have to rebase 0.3.20 :p

**Pull request merged**
