### PR TITLE
zipkin-collector-service is better configurable

### PR DESCRIPTION
**Pull request by kristofa**
Allow more configuration options to be configurable through
environment variables.

Especially being able to easily configure log level, sample rate
and number of queue workers is crucial for us.

### CODE REVIEW

**Comment by kristofa** [comment]
In our current zipkin setup we tweak `log level` (default debug level logs way too much), `queue num workers` and `sample rate`.  By using environment variables it means we also can configure these options when using `docker-zipkin`.

**Comment by kristofa** [comment]
If the environment variables are not specified I use the current default values.

**Comment by jamescway** [comment]
:+1:, maybe could use some simple docs?

**Comment by kristofa** [comment]
@jamescway Agree. I updated `README.md` with explanation of the new configurable parameters.

**Comment by jamescway** [comment]
looks great :)

**Pull request merged**
