### PR TITLE
Adding a go to trace textbox in the banner

### PR DESCRIPTION
**Pull request by gneokleo**
Adding a go to trace text box in the banner so you can immediately
jump to a trace if you know the hex value.

### CODE REVIEW

**Comment by gneokleo** [comment]
image

image

**Comment by codefromthecrypt** [comment]
Lgtm thanks!

**Comment by eirslett** [comment]
Nice feature! But could you put the javascript code together with the rest of the javascript? The input box could be mounted as a flight.js component.

**Comment by gneokleo** [comment]
Thanks for the review guys. I moved the code to where the rest of the javascript code is

**Comment by codefromthecrypt** [comment]
sweeeet

**Pull request merged**
