### PR TITLE
Adds property for X-Forwarded handling on redirect

### PR DESCRIPTION
**Pull request by codefromthecrypt**
See https://github.com/openzipkin/zipkin/pull/1627#issuecomment-326702774
See https://github.com/spring-projects/spring-boot/issues/6232

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
cc @naoman who raised the issue. I'm not sure if it is a simple workaround to have ELB do the path forwarding or not.

Any @shakuzen @wilkinsona do you know latest on X-Forwarded-For on spring boot? we are using default container on 1.5.6.RELEASE

**Comment by codefromthecrypt** [comment]
fwiw I tried adding the following to no avail:

```
server:
  tomcat:
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Forwarded-For
    port-header: X-Forwarded-Port
    protocol-header-https-value: https
```

Here's the redirect controller:
```java
  /** Make sure users who aren't familiar with /zipkin get to the right path */
  @RequestMapping(value = "/", method = GET)
  public ModelAndView redirectRoot() {
    return new ModelAndView("redirect:/zipkin/");
  }
```

**Comment by wilkinsona** [comment]
Looks like you're [missing `server.use-forward-headers: true`](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-tomcat-behind-a-proxy-server)

**Comment by codefromthecrypt** [comment]
@wilkinsona thanks.. almost there.. just `X-Forwarded-Host` isn't being picked up.. not really sure which setting would accomadate that.

```
server:
  use-forward-headers: true
  tomcat:
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Forwarded-For
    port-header: X-Forwarded-Port
    protocol-header-https-value: https
```

```
org.junit.ComparisonFailure: 
Expected :"https://zipkin.com:443/zipkin/"
Actual   :"https://localhost/zipkin/"
```

**Comment by codefromthecrypt** [comment]
I've removed `X-Forwarded-Host` from the test as `Host` is more typical anyway.

**Comment by codefromthecrypt** [comment]
Thanks @wilkinsona!

**Pull request merged**
