### PR TITLE
Apply prettier to zipkin-lens for automatic whitespace formatting.

### PR DESCRIPTION
**Pull request by anuraaga**
Note, this is just a strawman's proposal. Formatting preferences are not set-in-stone and I'm fine with just closing this PR if others don't like it. But figured it's worth giving one think on it.

I would say that automatic formatting using prettier is very common in the JS world, unlike say using Google Java Format for Java. As an example, our two most important dependencies, React and Material UI, both use it. So I think it can be said that it's idiomatic to use it - it's nice that's it's also "free" in terms of tooling, since it just integrates with our existing eslint. My personal opinion is not liking to think about formatting if a tool can do it for me, but interested in what others think on this.

### CODE REVIEW

**Review by codefromthecrypt — APPROVED** [review]
I feel less strongly about this than Java, so up to you and @tacigar

**Comment by tacigar** [comment]
Awesome!
I agree with using prettier.
But I'm wondering if it is possible to exactly match the rules of prettier and eslint.
Does not eslint show errors for code formatted by prettier?

**Comment by anuraaga** [comment]
Nope - we extend the eslint config with prettier-specific eslint configs which reconfigure other rules to not conflict. I've used this in other projects, and here too, I've never seen them fighting each other.

**Review by tacigar — APPROVED** [review]
Got it! LGTM~

**Pull request merged**
