### PR TITLE
Added support for prefetch count and upgraded RabbitMQ client lib to …

### PR DESCRIPTION
**Pull request by sufiannazim**
Added support for `prefetch count` to allow users to limit number of inflight/unacknowledged deliveries permitted on a consumer channel and upgraded RabbitMQ client library to latest supported version.

### CODE REVIEW

**Comment by jcchavezs** [comment]
Please rebase

**Comment by sufiannazim** [comment]
Ping @jcchavezs

**Review by jcchavezs — APPROVED** [review]
Thank you!

**Comment by sufiannazim** [comment]
@jcchavezs - How can I help to merge and close this pull request? it was opened on March 3rd and approved on Apr 22. Thanks!

**Comment by jcchavezs** [comment]
@shakuzen could you please give a review?

**Pull request closed without merging**
