### PR TITLE
Bintray auto publish

### PR DESCRIPTION
**Pull request by abesto**
Note: this is based off #573 

Problem: our workaround for making `bintrayUpload` work with an empty root project disabled all logic in the `bintrayUpload` task, which includes stuff like auto-publishing uploaded artifacts and maven central sync. 

This solution leaves the original logic in place, while still not publishing any artifacts for the (empty) root project, and also not failing the build process.

The output of `./gradlew bintrayUpload -i | grep 'Dry run'` with `dryRun = true`, note the "Published version" at the end and the lack of artifacts for the root project:

```
(Dry run) Created verion 'openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-aggregate/1.2.1-SNAPSHOT/zipkin-aggregate-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-aggregate/1.2.1-SNAPSHOT/zipkin-aggregate-1.2.1-SNAPSHOT.zip'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-aggregate/1.2.1-SNAPSHOT/zipkin-aggregate-1.2.1-SNAPSHOT.tar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-aggregate/1.2.1-SNAPSHOT/zipkin-aggregate-1.2.1-SNAPSHOT-all.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-aggregate/1.2.1-SNAPSHOT/zipkin-aggregate-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-anormdb/1.2.1-SNAPSHOT/zipkin-anormdb-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-anormdb/1.2.1-SNAPSHOT/zipkin-anormdb-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-cassandra/1.2.1-SNAPSHOT/zipkin-cassandra-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-cassandra/1.2.1-SNAPSHOT/zipkin-cassandra-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-collector/1.2.1-SNAPSHOT/zipkin-collector-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-collector/1.2.1-SNAPSHOT/zipkin-collector-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-collector-core/1.2.1-SNAPSHOT/zipkin-collector-core-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-collector-core/1.2.1-SNAPSHOT/zipkin-collector-core-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-collector-scribe/1.2.1-SNAPSHOT/zipkin-collector-scribe-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-collector-scribe/1.2.1-SNAPSHOT/zipkin-collector-scribe-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-collector-service/1.2.1-SNAPSHOT/zipkin-collector-service-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-collector-service/1.2.1-SNAPSHOT/zipkin-collector-service-1.2.1-SNAPSHOT.zip'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-collector-service/1.2.1-SNAPSHOT/zipkin-collector-service-1.2.1-SNAPSHOT.tar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-collector-service/1.2.1-SNAPSHOT/zipkin-collector-service-1.2.1-SNAPSHOT-all.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-collector-service/1.2.1-SNAPSHOT/zipkin-collector-service-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-common/1.2.1-SNAPSHOT/zipkin-common-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-common/1.2.1-SNAPSHOT/zipkin-common-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-example/1.2.1-SNAPSHOT/zipkin-example-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-example/1.2.1-SNAPSHOT/zipkin-example-1.2.1-SNAPSHOT.zip'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-example/1.2.1-SNAPSHOT/zipkin-example-1.2.1-SNAPSHOT.tar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-example/1.2.1-SNAPSHOT/zipkin-example-1.2.1-SNAPSHOT-all.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-example/1.2.1-SNAPSHOT/zipkin-example-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-query/1.2.1-SNAPSHOT/zipkin-query-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-query/1.2.1-SNAPSHOT/zipkin-query-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-query-core/1.2.1-SNAPSHOT/zipkin-query-core-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-query-core/1.2.1-SNAPSHOT/zipkin-query-core-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-query-service/1.2.1-SNAPSHOT/zipkin-query-service-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-query-service/1.2.1-SNAPSHOT/zipkin-query-service-1.2.1-SNAPSHOT.zip'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-query-service/1.2.1-SNAPSHOT/zipkin-query-service-1.2.1-SNAPSHOT.tar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-query-service/1.2.1-SNAPSHOT/zipkin-query-service-1.2.1-SNAPSHOT-all.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-query-service/1.2.1-SNAPSHOT/zipkin-query-service-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-receiver-kafka/1.2.1-SNAPSHOT/zipkin-receiver-kafka-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-receiver-kafka/1.2.1-SNAPSHOT/zipkin-receiver-kafka-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-receiver-scribe/1.2.1-SNAPSHOT/zipkin-receiver-scribe-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-receiver-scribe/1.2.1-SNAPSHOT/zipkin-receiver-scribe-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-redis/1.2.1-SNAPSHOT/zipkin-redis-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-redis/1.2.1-SNAPSHOT/zipkin-redis-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-redis-example/1.2.1-SNAPSHOT/zipkin-redis-example-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-redis-example/1.2.1-SNAPSHOT/zipkin-redis-example-1.2.1-SNAPSHOT.zip'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-redis-example/1.2.1-SNAPSHOT/zipkin-redis-example-1.2.1-SNAPSHOT.tar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-redis-example/1.2.1-SNAPSHOT/zipkin-redis-example-1.2.1-SNAPSHOT-all.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-redis-example/1.2.1-SNAPSHOT/zipkin-redis-example-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-sampler/1.2.1-SNAPSHOT/zipkin-sampler-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-sampler/1.2.1-SNAPSHOT/zipkin-sampler-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-scrooge/1.2.1-SNAPSHOT/zipkin-scrooge-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-scrooge/1.2.1-SNAPSHOT/zipkin-scrooge-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-thrift/1.2.1-SNAPSHOT/zipkin-thrift-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-thrift/1.2.1-SNAPSHOT/zipkin-thrift-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-tracegen/1.2.1-SNAPSHOT/zipkin-tracegen-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-tracegen/1.2.1-SNAPSHOT/zipkin-tracegen-1.2.1-SNAPSHOT.zip'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-tracegen/1.2.1-SNAPSHOT/zipkin-tracegen-1.2.1-SNAPSHOT.tar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-tracegen/1.2.1-SNAPSHOT/zipkin-tracegen-1.2.1-SNAPSHOT-all.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-tracegen/1.2.1-SNAPSHOT/zipkin-tracegen-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-web/1.2.1-SNAPSHOT/zipkin-web-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-web/1.2.1-SNAPSHOT/zipkin-web-1.2.1-SNAPSHOT.zip'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-web/1.2.1-SNAPSHOT/zipkin-web-1.2.1-SNAPSHOT.tar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-web/1.2.1-SNAPSHOT/zipkin-web-1.2.1-SNAPSHOT-all.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-web/1.2.1-SNAPSHOT/zipkin-web-1.2.1-SNAPSHOT.pom'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-zookeeper/1.2.1-SNAPSHOT/zipkin-zookeeper-1.2.1-SNAPSHOT.jar'.
(Dry run) Uploaded to 'https://api.bintray.com/content/openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT/io/zipkin/zipkin-zookeeper/1.2.1-SNAPSHOT/zipkin-zookeeper-1.2.1-SNAPSHOT.pom'.
(Dry run) Pulished verion 'openzipkin/zipkin/zipkin/1.2.1-SNAPSHOT'.
```

### CODE REVIEW

**Comment by abesto** [comment]
+cc @jamescway @adriancole

**Comment by rtyler** [comment]
:+1:

**Comment by codefromthecrypt** [comment]
+1

**Comment by jamescway** [comment]
nice alternate workaround :smile:  :+1:

**Pull request merged**
