### PR TITLE
Fix bugs related to i18n

### PR DESCRIPTION
**Pull request by tacigar**
https://github.com/openzipkin/zipkin/issues/2239#issuecomment-438589858

### CODE REVIEW

**Comment by tacigar** [comment]
@adriancole 
I'm in the process of Apache's ICLA now, is it OK?
If not, I close this PR.
And I'll remake it after I'm accepted.

**Review by codefromthecrypt — APPROVED** [review]
so subtle amazing you figure this out

**Comment by codefromthecrypt** [comment]
this repo not Apache yet. I think it will be ok especially if you are in
progress.

**Review by shakuzen — APPROVED** [review]

**Comment by tacigar** [comment]
@adriancole 
I see
Thank you~! :smile:

**Comment by tacigar** [comment]
But the same bug still occurs on the TraceViewer page.
This is a bit complicated problem, so I need to take a little more thought...
I will make a PR if I think of a good plan :+1:

**Pull request merged**
