### PR TITLE
Update sidebar and header design

### PR DESCRIPTION
**Pull request by tacigar**
Remove Sidebar and update Header design

**Before:**

スクリーンショット 2020-08-09 2 04 13

**After:**

スクリーンショット 2020-08-15 18 06 20
スクリーンショット 2020-08-15 18 06 20のコピー

### CODE REVIEW

**Comment by jorgheymans** [comment]
Thanks @tacigar, if it's not too much effort could you provide before/after (side-by-side whatever) screenshots perhaps ? Would make it easier for us (well at least for me) to follow and comment on the the design update.

**Comment by codefromthecrypt** [comment]
before / after screenshot possibly annotating by drawing on after screen
shot to say what's important will be helpful to folks less familiar with
nuance to know the specific changes

**Comment by tacigar** [comment]
Update the design
PTAL~

**Comment by codefromthecrypt** [comment]
is after screenshot up to date?

**Comment by codefromthecrypt** [comment]
also since I think there was a lot of offline feedback I think the design is stabilizing, might be time to review and decide which unit tests should be added to cement the code here works

**Comment by tacigar** [comment]
yes, now these screenshots are up to date 🙇

**Comment by codefromthecrypt** [comment]
Thanks for so much effort here Igarashi!

**Comment by tacigar** [comment]
Thank you so much!

**Pull request merged**
