### PR TITLE
add note on security since it has come up several times on gitter

### PR DESCRIPTION
**Pull request by jorgheymans**
brief note basically saying that zipkin-ui does not handle security itself.

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
sounds good, but should this note be in the server readme, here or both?

**Comment by jorgheymans** [comment]
Good point, maybe we should also point out then that there are different
entry points to consider (browser URL vs rest api). Most people don't
distinguish between them initially. But layer they might want to have
different security rules for these. I'll revise and update. Maybe it will
be more clear where to put it as well then.

Op wo 4 apr. 2018 01:56 schreef Adrian Cole <notifications@github.com>:

**Comment by jorgheymans** [comment]
added note on the endpoints.

as to how to secure data ingestion via the api that should be put in zipkin-server and somewhere in brave because it affects them both, should be done in a different PR.

**Comment by codefromthecrypt** [comment]
Might be useful to link to our httpd doc somehow as proxying the UI is a
bit tricky
https://github.com/openzipkin/zipkin/tree/master/zipkin-ui#apache-http-as-a-zipkin-reverse-proxy

**Comment by jorgheymans** [comment]
done.

**Comment by codefromthecrypt** [comment]
thanks so much!

**Pull request merged**
