### PR TITLE
Keep sort order in hidden input

### PR DESCRIPTION
**Pull request by synk**
This patch enables zipkin-web keep sort order in hidden input. Without this patch you have to set sort order every submit.

### CODE REVIEW

**Comment by sprsquish** [comment]
@synk why'd you close this?

I like the idea and wanted to pull it in eventually and make some tweaks to it.

**Comment by synk** [comment]
Sorry to be confused...
I will be glad if you pull this!

**Comment by tdrisdelle** [comment]
Looking forward to this one!

**Comment by codefromthecrypt** [comment]
@eirslett wdyt about this one?

**Comment by eirslett** [comment]
+1

**Comment by codefromthecrypt** [comment]
oops. this patch no longer applies. @synk you mind rebasing it?

**Comment by codefromthecrypt** [comment]
closing as we want to keep the pull request queue fresh and relevant. Please ping if you get around to rebasing etc!

**Pull request closed without merging**
